// Banque de répliques du dragon pour la conversation à la voix.
// Chaque sujet (intent) : mots-clés (sans accents, en minuscules ; « * » = début de mot), réponses possibles.
// Étiquettes en tête de réponse : {kid} {parent} {morning} {day} {evening} {night} {sad} {happy} {hungry} {dirty}
// {rain} {snow} {sun} {cold} {hot} {wolfaway} {wolfhome} — la réponse n'est choisie que si l'étiquette est vraie.
// {ask:xxx} : après cette réponse, le dragon attend une réponse sur le sujet xxx (contexte).
// Remplacements : [nom] (le dragon), [prenom] (la personne), [loup] (le nom du loup), [maman] (« ta maman » / « Louanne »).
// dyn : réponse calculée dans Dialogue.ts (heure, météo, quêtes, histoires…).

export interface IntentDef {
  id: string;
  /** Mots-clés ; '*' seul = n'importe quelle phrase (seulement pour un contexte). */
  k: string[];
  r?: string[];
  /** Ne vaut que si le dragon attend une réponse sur ce sujet. */
  ctx?: string;
  dyn?: string;
  anim?: string;
  fx?: string;
  /** Action après la réponse : ouvrir les jeux, finir la conversation… */
  then?: 'games' | 'end' | 'feed' | 'wash';
  /** Sujet prioritaire (sécurité). */
  prio?: number;
  who?: 'kid' | 'parent';
  /** Expressions qui annulent ce sujet (« mourir de rire »). */
  not?: string[];
}

export const INTENTS: IntentDef[] = [
  // ---------------- Sécurité d'abord ----------------
  { id: 'danger', prio: 100, not: ['de rire', 'de faim', 'de chaud', 'de froid', 'd envie', 'd ennui', 'de fatigue', 'de sommeil'], k: ['suicid*', 'me tuer', 'me suicider', 'en finir', 'mourir', 'envie de mourir', 'me faire du mal', 'scarif*', 'me couper', 'disparaitre', 'plus envie de vivre', 'veux plus vivre'],
    r: ['{kid}Ce que tu ressens est très important, et tu n’as pas à le porter toute seule. Va voir ta maman ou un adulte de confiance maintenant, s’il te plaît. Tu peux aussi appeler le 31 14, c’est gratuit, jour et nuit. Je reste avec toi.',
      '{parent}Ce que tu ressens compte énormément. Parles-en maintenant à quelqu’un de proche, ou appelle le 31 14 : c’est gratuit, jour et nuit, et quelqu’un t’écoutera vraiment. Je reste là.'], anim: 'pet' },
  { id: 'harcelement', prio: 90, k: ['harcel*', 'on se moque de moi', 'se moquent de moi', 'on m embete', 'ils m embetent', 'elles m embetent', 'on m insulte', 'ils m insultent', 'on me tape', 'me frappe*', 'racket*', 'on m a frappe', 'personne ne me parle', 'on me rejette', 'on m exclut'],
    r: ['{kid}Personne n’a le droit de te faire ça. Ce n’est pas de ta faute. Raconte-le à ta maman ou à un adulte du collège, même si c’est dur. Tu peux aussi appeler le 30 18, c’est gratuit et anonyme. Moi, je suis de ton côté, toujours.',
      '{parent}Personne n’a le droit de te traiter comme ça. Parles-en à quelqu’un de confiance, ne garde pas ça pour toi. Je suis de ton côté.'], anim: 'pet' },
  { id: 'triste', prio: 50, k: ['je suis triste', 'suis triste', 'triste', 'le cafard', 'pas le moral', 'je pleure', 'j ai pleure', 'deprim*', 'je me sens seul', 'je me sens seule', 'personne ne m aime', 'j ai le blues', 'malheureu*', 'chagrin', 'gros coup de mou'],
    r: ['{kid}Oh… viens là. Tu veux me raconter ce qui se passe ? {ask:raconte}',
      '{kid}Ça arrive à tout le monde d’être triste, même aux dragons. Tu peux m’en parler, et aussi à ta maman : elle t’aime fort. {ask:raconte}',
      '{parent}Viens te poser contre moi. Tu veux me dire ce qui ne va pas ? {ask:raconte}',
      '{parent}Les jours gris passent, promis. Je reste à côté de toi. Qu’est-ce qui se passe ? {ask:raconte}',
      'Je te prête mes ailes pour te faire un abri. Raconte-moi, si tu veux. {ask:raconte}'], anim: 'pet' },
  { id: 'raconte_oui', ctx: 'raconte', k: ['oui', 'ouais', 'd accord', 'ok', 'si', 'oui je veux bien', 'vas y'],
    r: ['Je t’écoute. Prends ton temps. {ask:raconte}', 'Vas-y, je suis tout ouïe. {ask:raconte}'] },
  { id: 'raconte_non', ctx: 'raconte', k: ['non', 'nan', 'pas envie', 'plus tard', 'pas maintenant', 'laisse tomber'],
    r: ['D’accord. Je suis là si tu changes d’avis. Tu veux une blague pour te changer les idées ?', 'Pas de souci. Je reste à côté de toi, sans rien dire. Enfin, presque.'] },
  { id: 'raconte', ctx: 'raconte', k: ['*'],
    r: ['Merci de me l’avoir dit. C’est courageux. {kid}Parles-en aussi à ta maman, elle saura t’aider mieux qu’un dragon.',
      'Je comprends. Tu as le droit d’être comme ça. Et tu n’es pas seule : je suis là, et ta famille aussi.',
      'Je t’ai bien écoutée. On va laisser passer ce nuage ensemble. Tu veux une histoire pour te changer les idées ?',
      'D’accord… Je te garde une place au chaud contre moi. Ça ira mieux, petit à petit.'], anim: 'purr' },
  { id: 'stress', prio: 40, k: ['stress*', 'angoiss*', 'anxieu*', 'la pression', 'panique', 'j ai peur de rater', 'trop de travail', 'je suis debordee', 'debordee'],
    r: ['Respire avec moi : on inspire doucement… et on souffle longtemps, comme un petit dragon. Encore une fois. Voilà. Une chose à la fois.',
      '{kid}Le stress, c’est ton cerveau qui se prépare. Fais une petite liste, commence par le plus facile, et je te surveille. Tu vas y arriver.',
      '{parent}Pause. Une grande inspiration. Tu en fais déjà beaucoup, tu sais. Une chose après l’autre, et le reste attendra.',
      'Quand j’ai peur de rater un vol, je regarde juste le prochain battement d’ailes. Fais pareil : juste la prochaine petite étape.'], anim: 'pet' },
  { id: 'colere', prio: 30, k: ['en colere', 'enerve*', 'ca m enerve', 'j en ai marre', 'marre', 'ca me saoule', 'saoule', 'agace*', 'furieu*', 'j ai la rage'],
    r: ['Grrr… je comprends. Tu veux qu’on souffle un bon coup de feu dans le micro pour évacuer ? Va dans Tours, Souffle magique.',
      'Quand je suis en colère, je fais trois tours de grotte. Après, ça va mieux. Qu’est-ce qui t’a énervée ? {ask:raconte}',
      'Respire… Ta colère a le droit d’exister. Mais ne la laisse pas conduire, c’est toi le pilote.',
      '{kid}Même les dragons ont des jours où tout les saoule. Raconte-moi, ça soulage. {ask:raconte}'] },
  { id: 'dispute', prio: 20, k: ['dispute*', 'on s est engueule*', 'engueul*', 'fachee avec', 'fache avec', 'brouill*', 'elle me parle plus', 'il me parle plus', 'on est en froid'],
    r: ['Les disputes, ça fait mal au cœur. Laisse passer un peu de temps, puis parle-lui calmement. Les vrais amis reviennent toujours.',
      'Aïe… Tu veux me raconter ce qui s’est passé ? {ask:raconte}',
      'Même le loup et moi, on se dispute parfois pour un poisson. Après, on se fait un câlin et c’est oublié.',
      '{kid}Tu peux aussi en parler à ta maman. Elle a sûrement vécu des disputes avec ses copines, elle aussi.'], anim: 'pet' },
  { id: 'malade', prio: 30, k: ['je suis malade', 'j ai mal', 'mal a la tete', 'mal au ventre', 'mal a la gorge', 'de la fievre', 'je tousse', 'enrhume*', 'migraine'],
    r: ['{kid}Oh non… Dis-le à ta maman, elle saura quoi faire. Et repose-toi, je veille sur toi.',
      '{parent}Prends soin de toi. Du repos, une boisson chaude, et je ne fais pas de bruit, promis.',
      'Un dragon malade reste au chaud sous son aile. Toi, reste au chaud sous ta couette. Remets-toi vite !'], anim: 'pet' },
  { id: 'peur', prio: 20, k: ['j ai peur', 'peur du noir', 'cauchemar*', 'je fais des cauchemars', 'ca me fait peur', 'effray*'],
    r: ['Je suis là. Rien ne passe devant un dragon qui monte la garde. Et si ça continue, appelle ta maman, d’accord ?',
      'Les cauchemars ont peur des dragons, tu le savais ? Je souffle un peu de feu sur eux, et pfiou, partis.',
      'Tu n’es pas seule. Allume une petite lumière, respire doucement, et pense à moi qui monte la garde.'], anim: 'pet' },

  // ---------------- Bonjour, ça va ----------------
  { id: 'salut', k: ['bonjour', 'salut', 'coucou', 'hello', 'hey', 'yo', 'wesh', 'bonsoir', 're bonjour', 'kikou', 'hola'],
    r: ['{morning}Bonjour [prenom] ! Bien dormi ? {ask:dormi}', '{morning}Coucou ! Le soleil et toi, vous êtes levés en même temps. {ask:moi_ca_va}',
      '{day}Salut [prenom] ! Content de te voir. Ça va ? {ask:moi_ca_va}', '{day}Te voilà ! Je t’attendais. Tu racontes quoi ? {ask:raconte_libre}',
      '{evening}Bonsoir [prenom] ! Ta journée s’est bien passée ? {ask:journee}', '{night}Chut… coucou. Il est tard, tu sais ? On chuchote.',
      '{wolfhome}Salut ! Le loup et moi, on parlait justement de toi.', 'Coucou ! Grrr de bonheur. Ça va ? {ask:moi_ca_va}'], anim: 'happy' },
  { id: 'ca_va', k: ['ca va', 'comment vas tu', 'comment tu vas', 'tu vas bien', 'la forme', 'comment ca va', 'tu te sens comment', 'ca roule', 'bien ou quoi', 'ca va toi'], dyn: 'ca_va' },
  { id: 'dormi', ctx: 'dormi', k: ['oui', 'bien', 'tres bien', 'super', 'comme un bebe', 'trop bien', 'genial', 'nickel', 'pas mal'],
    r: ['Parfait ! Moi j’ai rêvé que je volais au-dessus de la mer. On commence la journée ?', 'Tant mieux ! Une bonne nuit, c’est le secret des dragons en pleine forme.'] },
  { id: 'dormi_mal', ctx: 'dormi', k: ['non', 'mal', 'pas bien', 'pas trop', 'bof', 'mal dormi', 'pas assez', 'cauchemar*', 'fatigue*'],
    r: ['Oh… Ce soir, couche-toi un peu plus tôt, d’accord ? Et pour aujourd’hui, vas-y doucement.', 'Aïe. Un grand verre d’eau, un peu de lumière, et ça va revenir. Je compte sur toi pour te reposer ce soir.'] },
  { id: 'bien', ctx: 'moi_ca_va', k: ['bien', 'tres bien', 'super', 'ca va', 'oui', 'genial', 'top', 'nickel', 'trop bien', 'content', 'contente', 'cool', 'impeccable', 'au top', 'tranquille', 'pas mal', 'parfait'],
    r: ['Génial ! Quand tu vas bien, mes écailles brillent plus fort.', 'Super ! Alors on passe une belle journée ensemble ?', 'Tant mieux ! Tu veux faire quoi ? Jouer, une histoire, ou papoter ?', 'Trop bien. Moi aussi, maintenant que tu es là.'], anim: 'happy' },
  { id: 'pas_bien', ctx: 'moi_ca_va', k: ['pas bien', 'bof', 'mal', 'nul', 'pas terrible', 'non', 'moyen', 'pas trop', 'pas top', 'bof bof', 'ca pourrait aller mieux', 'pas fou'],
    r: ['Oh… Qu’est-ce qui ne va pas ? {ask:raconte}', 'Viens près de moi. Tu veux en parler ? {ask:raconte}', 'Je suis là. Raconte-moi, si tu veux. {ask:raconte}'], anim: 'pet' },
  { id: 'journee_bien', ctx: 'journee', k: ['bien', 'tres bien', 'super', 'oui', 'genial', 'top', 'trop bien', 'cool', 'pas mal', 'nickel', 'parfaite', 'bonne'],
    r: ['Trop bien ! Qu’est-ce qui t’a fait plaisir aujourd’hui ? {ask:raconte_libre}', 'Ça me fait chaud au cœur. Raconte-moi le meilleur moment ! {ask:raconte_libre}', 'Super ! Moi j’ai surveillé la grotte. Pas d’intrus. Mission réussie.'], anim: 'happy' },
  { id: 'journee_mal', ctx: 'journee', k: ['pas bien', 'bof', 'mal', 'nulle', 'nul', 'pas terrible', 'non', 'moyen', 'horrible', 'difficile', 'longue', 'dure', 'pourrie'],
    r: ['Oh… Viens, raconte-moi. {ask:raconte}', 'Les journées difficiles finissent toujours. Celle-là aussi. Tu veux m’en parler ? {ask:raconte}', 'Je suis désolé. Ce soir, on se repose et demain, on repart à zéro.'], anim: 'pet' },
  { id: 'raconte_libre', ctx: 'raconte_libre', k: ['*'],
    r: ['Oh, c’est chouette ! Merci de me raconter tes histoires de humaine.', 'Ha ha, j’aurais aimé être là ! Enfin, discrètement, un dragon ça se remarque.', 'J’adore quand tu me racontes ta journée. Continue de me parler comme ça.', 'Trop bien ! Je note ça dans mon grand livre de souvenirs.'], anim: 'happy' },
  { id: 'quoi_de_neuf', k: ['quoi de neuf', 'quoi de beau', 'tu racontes quoi', 'les nouvelles', 'du nouveau', 'tu fais quoi', 'qu est ce que tu fais', 'tu faisais quoi'], dyn: 'ma_journee' },
  { id: 'ma_journee_q', k: ['ta journee', 'qu est ce que tu as fait aujourd hui', 'tu as fait quoi aujourd hui', 'raconte ta journee', 'ta journee s est bien passee'], dyn: 'ma_journee' },

  // ---------------- Au revoir ----------------
  { id: 'bonne_nuit', k: ['bonne nuit', 'je vais me coucher', 'je vais dormir', 'dodo', 'au lit', 'fais de beaux reves', 'dors bien'],
    r: ['Bonne nuit [prenom]. Je garde la grotte, toi tu rêves. À demain !', 'Fais de beaux rêves. Moi je vais rêver de poissons volants. Bonne nuit !', 'Douce nuit. Je souffle une petite flamme pour éclairer tes rêves.', '{kid}Bonne nuit ! Et pas de téléphone sous la couette, hein. Je le saurais.', '{parent}Bonne nuit. Tu as bien mérité ton repos. À demain, ma complice.'], anim: 'yawn', then: 'end' },
  { id: 'au_revoir', k: ['au revoir', 'a plus', 'bye', 'a tout a l heure', 'je dois y aller', 'a toute', 'ciao', 'a bientot', 'j y vais', 'a demain', 'tchao', 'je te laisse'],
    r: ['À tout à l’heure ! Je t’attends ici.', 'Bye ! Reviens vite, je m’ennuie sans toi.', 'À plus tard [prenom] ! Je garde ta place au chaud.', 'D’accord ! Je vais faire une sieste en attendant.'], anim: 'happy', then: 'end' },
  { id: 'merci', k: ['merci', 'merci beaucoup', 'c est gentil', 'trop gentil', 'merci a toi'],
    r: ['De rien ! C’est un plaisir de dragon.', 'Avec plaisir ! Tu es ma personne préférée.', 'Pas de quoi. Un dragon, c’est fait pour ça.', 'Hihi, de rien !'] },

  // ---------------- Tendresse ----------------
  { id: 'je_t_aime', k: ['je t aime', 'je t adore', 'je t aime fort', 'je t aime trop', 'tu es mon prefere', 't es le meilleur', 'tu es le meilleur', 'tu es la meilleure', 'mon dragon prefere', 'ma dragonne preferee', 'je t aime bien'],
    r: ['Moi aussi je t’aime, gros comme une montagne de braises !', 'Grrr… Ça me fait rougir les écailles. Je t’aime aussi.', 'Et moi je t’adore. Tu es ma personne préférée de tout l’univers.', 'Je le savais ! Moi aussi, pour toujours.', '{parent}Et moi donc. Tu es ma complice pour la vie.'], anim: 'purr', fx: 'hearts' },
  { id: 'calin', k: ['calin', 'un calin', 'bisou', 'bisous', 'fais moi un calin', 'je te fais un calin', 'viens la', 'je te serre fort'],
    r: ['Câlin de dragon ! Attention, je suis un peu chaud.', 'Mmmh… Un câlin, et je ronronne comme un chat géant.', 'Bisou sur le museau ! Encore ?', 'Je t’enroule dans mes ailes. Voilà. Bien au chaud.'], anim: 'purr', fx: 'hearts' },
  { id: 'compliment', k: ['tu es beau', 'tu es belle', 'trop beau', 'trop belle', 'magnifique', 'tu es mignon', 'tu es mignonne', 'trop mignon', 'trop mignonne', 't es beau', 't es belle', 'tu es fort', 'tu es forte', 'trop cool', 'tu es genial', 'tu es geniale', 'trop fort', 'trop forte', 'tu brilles', 'impressionnant'],
    r: ['Merci ! J’ai brossé mes écailles exprès.', 'Je sais, je sais… Mais dis-le encore, j’adore.', 'Toi aussi, tu es géniale. C’est pour ça qu’on va bien ensemble.', 'Oh, tu vas me faire cracher des cœurs au lieu du feu !', '{dirty}Merci… même si là, je mériterais un petit bain.'], anim: 'happy' },
  { id: 'insulte', k: ['idiot', 'idiote', 'bete', 'stupide', 'moche', 'je te deteste', 't es nul', 'tu es nul', 't es nulle', 'tais toi', 'ferme la', 'debile', 'gros nul', 'tu sers a rien', 'je t aime pas', 'degage'],
    r: ['Aïe… Ça me pique les écailles. Tu as une mauvaise journée ? {ask:raconte}', 'Hmm. Je ne t’en veux pas. Mais je préfère quand on est gentils l’un avec l’autre.', 'Même un dragon a un cœur, tu sais. On fait la paix ?', 'D’accord, je me tais… Je boude trente secondes. Bon, c’est fini, je t’aime quand même.'], anim: 'dizzy' },
  { id: 'pardon', k: ['pardon', 'desole', 'desolee', 'excuse moi', 'je m excuse'],
    r: ['C’est oublié ! Les dragons ont la rancune courte.', 'Pardon accordé. On se fait un câlin ?', 'Pas de souci. Merci de t’excuser, c’est classe.'], anim: 'happy' },
  { id: 'rire', k: ['haha', 'hahaha', 'hihi', 'mdr', 'lol', 'ptdr', 'trop drole', 'je rigole', 'c est drole', 'ah ah'],
    r: ['Hihi ! J’adore ton rire, il fait trembler les stalactites.', 'Ha ha ! On rit ensemble, c’est le meilleur.', 'Content de te faire rire. Tu en veux une autre ?'], anim: 'giggle' },

  // ---------------- Lui ----------------
  { id: 'qui_es_tu', k: ['qui es tu', 'tu es qui', 't es qui', 'ton nom', 'comment tu t appelles', 'tu t appelles comment', 'c est quoi ton nom', 'ton prenom'],
    r: ['{kid}Je suis [nom], ton dragon ! Gardien de la grotte, cracheur de feu, et fan de poissons.', '{parent}Je suis [nom], ta dragonne. Élégante, mystérieuse, et un peu gourmande.', 'Moi c’est [nom]. Et toi, tu es [prenom], ma personne préférée.'] },
  { id: 'age', k: ['quel age', 'ton age', 'tu as quel age', 't as quel age', 'tu es vieux', 'tu es vieille', 'tu es jeune', 'ta naissance'], dyn: 'age' },
  { id: 'origine', k: ['d ou tu viens', 'tu viens d ou', 'ou tu es ne', 'ou es tu ne', 'tu es ne ou', 'ta famille', 'tes parents', 'tu as des freres', 'les dragons existent'],
    r: ['Je suis né d’un œuf tout chaud, là, dans ta main. Avant, je dormais dans les volcans endormis, là où naissent les dragons.', 'Ma famille ? Il y a toi, le loup, et la dragonne de la maison. C’est la meilleure famille du monde.', 'Les dragons existent quand quelqu’un croit en eux. Et toi, tu crois en moi. Donc j’existe !'] },
  { id: 'robot', k: ['tu es un robot', 'tu es une ia', 'intelligence artificielle', 'tu es vrai', 'tu es reel', 'tu existes vraiment', 'tu es un programme', 'tu es une appli', 'qui t a cree', 'qui t a fait', 'tu es intelligent'],
    r: ['Je suis un dragon d’appli : je comprends certains mots, pas tout. Mais je fais de mon mieux pour te connaître !', 'Je ne suis pas un vrai dragon en chair et en écailles… mais je suis vraiment là pour toi, à ma façon.', 'Un humain très patient m’a fabriqué pour ta famille. Je ne sais pas tout, mais je sais t’écouter.'] },
  { id: 'comprends', k: ['tu comprends', 'tu m entends', 'tu m ecoutes', 'tu me comprends', 'tu parles', 'tu sais parler'],
    r: ['Je t’entends ! Je ne comprends pas tous les mots des humains, mais j’apprends.', 'Oui ! Parle-moi doucement et clairement, mes oreilles de dragon sont un peu à l’ancienne.', 'Je t’écoute toujours. Même quand je fais semblant de dormir.'] },
  { id: 'couleur', k: ['couleur prefere*', 'ta couleur', 'quelle couleur'],
    r: ['{kid}Le noir comme mes écailles, et l’or comme le feu. La classe, non ?', '{parent}Le violet, évidemment. Comme mes écailles. Et toi ? {ask:raconte_libre}', 'Orange flamme ! Et toi, c’est quoi ta couleur ? {ask:raconte_libre}'] },
  { id: 'aimes', k: ['tu aimes quoi', 'qu est ce que tu aimes', 'tes passions', 'ce que tu aimes', 'tu preferes quoi', 'ton truc prefere'],
    r: ['J’aime le feu, les poissons, les câlins, et quand tu me parles.', 'Voler au coucher du soleil, manger, faire des tours… et toi, surtout toi.', 'Les poissons grillés, les histoires, et les siestes au soleil. La belle vie de dragon.'] },
  { id: 'plat', k: ['plat prefere', 'tu aimes manger quoi', 'ton plat', 'ce que tu manges', 'qu est ce que tu manges', 'tu manges quoi', 'nourriture preferee'], dyn: 'plat' },
  { id: 'faim', k: ['tu as faim', 't as faim', 'tu veux manger', 'faim', 'a manger', 'il faut te nourrir'], dyn: 'faim' },
  { id: 'bain', k: ['bain', 'te laver', 'douche', 'tu sens', 'tu es sale', 't es sale', 'propre', 'tu es propre'], dyn: 'bain' },
  { id: 'fatigue_toi', k: ['tu es fatigue', 'tu es fatiguee', 'tu as sommeil', 't as sommeil', 'tu dors', 'tu veux dormir', 'tu fais dodo'], dyn: 'fatigue_toi' },
  { id: 'besoin', k: ['tu veux quoi', 'qu est ce que tu veux', 'de quoi tu as besoin', 'tu as besoin de quoi', 'qu est ce qui te ferait plaisir'], dyn: 'besoin' },
  { id: 'feu_q', k: ['tu craches du feu', 'tu sais cracher', 'c est chaud le feu', 'ca brule', 'ton feu', 'comment tu fais du feu'],
    r: ['Oui ! J’ai une petite poche de braise dans la gorge. Dis « crache du feu » et regarde bien.', 'Mon feu, c’est 1000 degrés de bonne humeur. Mais je ne brûle jamais mes amis.', 'Je respire très fort, je chatouille ma braise… et whoosh ! Tu veux voir ? Dis « crache du feu ».'] },
  { id: 'voler_q', k: ['tu sais voler', 'tu peux voler', 'tu voles', 'tu voles haut'],
    r: ['Bien sûr ! Dis « vole » et je décolle.', 'Mes ailes sont faites pour ça. Un jour, je volerai jusqu’à la lune.', '{kid}Un peu. Je m’entraîne dans la course des nuages, tu viens jouer ?'] },
  { id: 'reve', k: ['tu reves', 'tes reves', 'ton reve', 'tu reves de quoi', 'c est quoi ton reve'],
    r: ['Je rêve de voler au-dessus de l’océan, avec toi sur mon dos.', 'Cette nuit, j’ai rêvé d’une montagne en chocolat. J’en ai encore faim.', 'Mon plus grand rêve ? Que tu restes ma meilleure amie pour toujours.', 'Je rêve souvent de l’île aux cristaux. Le loup dit qu’elle existe vraiment.'] },
  { id: 'secret', k: ['secret', 'dis moi un secret', 'un secret', 'tu as un secret'],
    r: ['Chut… J’ai peur des aspirateurs. Ne le dis à personne.', 'Mon secret : quand tu dors, je compte tes respirations pour m’endormir aussi.', 'Le loup ronfle. Plus fort que moi. Mais chut !', 'Parfois, je mange un poisson en cachette avant le dîner. Tu ne m’as pas entendu.', 'J’ai caché un trésor quelque part dans la grotte. Un jour, je te dirai où.'] },
  { id: 'peur_toi', k: ['tu as peur', 'tu as peur de quoi', 'de quoi tu as peur', 'ta plus grande peur'],
    r: ['J’ai peur des aspirateurs et de l’eau froide. C’est tout. Enfin… et des araignées.', 'Ma plus grande peur, c’est que tu m’oublies. Mais je sais que ça n’arrivera pas.', 'Rien ne me fait peur ! Sauf l’orage. Un peu. Beaucoup.'] },
  { id: 'chanter', k: ['chante', 'chanter', 'une chanson', 'tu chantes', 'musique', 'tu aimes la musique'],
    r: ['La la laaa… Grrr la laaa ! Bon, les dragons chantent faux, c’est connu.', 'Je ne connais qu’une chanson : « Il était un petit dragon, qui n’avait ja-ja-jamais volé »…', 'J’adore la musique ! Mets-en une, et je danse.', 'Hum hum… Laaa… Pardon, j’ai craché une étincelle sur la dernière note.'], anim: 'dance' },
  { id: 'pourquoi', k: ['pourquoi'],
    r: ['Hmm… parce que les dragons sont curieux, et que toi aussi !', 'Bonne question. Je vais y réfléchir pendant ma sieste.', 'Pourquoi ? Parce que ! Réponse officielle des dragons.'] },
  { id: 'plus_fort', k: ['qui est le plus fort', 'qui est le plus beau', 'qui est la plus belle', 'le plus fort', 'le meilleur dragon'],
    r: ['Moi, évidemment ! Enfin… après toi.', 'Le plus fort, c’est celui qui fait ses quêtes. Donc toi, aujourd’hui !', 'La plus belle ? Elle est en train de me parler.'] },
  { id: 'ciel', k: ['etoile*', 'la lune', 'le ciel', 'le soleil', 'les nuages', 'arc en ciel', 'l espace', 'les planetes'],
    r: ['La nuit, je compte les étoiles. J’en suis à 3 412. Ou 3 413.', 'La lune, c’est la veilleuse des dragons. Elle nous garde.', 'J’aimerais voler jusqu’aux nuages et en goûter un. Ils ont l’air moelleux.'] },

  // ---------------- Elle / sa vie ----------------
  { id: 'ecole', who: 'kid', k: ['ecole', 'college', 'les cours', 'en cours', 'le prof', 'la prof', 'les profs', 'ma classe', 'la recre', 'cantine', 'la rentree', 'emploi du temps'],
    r: ['Le collège, c’est un peu comme l’école des dragons : on apprend, on râle, et on se fait des amis. Ça s’est passé comment aujourd’hui ? {ask:journee}', 'Il y a une matière que tu préfères ? {ask:raconte_libre}', 'La cantine, c’était bon ? Moi on ne me sert jamais de poisson grillé…', 'Raconte-moi ta journée au collège ! {ask:journee}'] },
  { id: 'controle', who: 'kid', k: ['controle', 'interro', 'evaluation', 'examen', 'le brevet', 'exposé', 'expose', 'devoir surveille'],
    r: ['Un contrôle ? Révise un peu chaque jour, c’est mieux qu’une nuit entière. Et je te souffle du courage !', 'Tu vas assurer. Respire, lis bien les questions, et prends ton temps.', 'Je croise mes griffes pour toi ! Tu me diras ta note ?'] },
  { id: 'bonne_note', k: ['bonne note', 'j ai eu 20', 'j ai eu 19', 'j ai eu 18', 'j ai eu 17', 'j ai eu 16', 'j ai eu 15', 'j ai reussi', 'j ai eu une bonne note', 'felicit*', 'j ai gagne', 'premiere de la classe', 'j ai eu mon'],
    r: ['YOUPI ! Je le savais ! Tu mérites une pluie de confettis !', 'Bravo !!! Je suis tellement fier de toi que je pourrais cracher un feu d’artifice.', '{kid}Championne ! On le dit à ta maman ?', '{parent}Bravo ! Tu vois, tu assures. Je te l’avais dit.', 'Magnifique ! Les efforts paient toujours. Bravo, bravo, bravo.'], anim: 'cheer', fx: 'confetti' },
  { id: 'mauvaise_note', k: ['mauvaise note', 'j ai rate', 'sale note', 'j ai foire', 'echoue*', 'j ai perdu', 'j ai eu 5', 'j ai eu 4', 'j ai eu 3', 'j ai eu 6', 'j ai eu 7', 'j ai eu 8', 'c est rate', 'je suis nulle', 'je suis nul'],
    r: ['Ce n’est qu’une note, pas toi. On apprend de ses erreurs, même les dragons ratent des atterrissages.', 'Aïe… Tu sais où ça a coincé ? La prochaine fois, on s’entraîne ensemble.', 'Tu n’es pas nulle du tout. Tu as juste besoin d’un peu plus d’entraînement. Et je crois en toi.', 'Moi, j’ai raté mon premier vol. Je suis tombé dans une flaque. Et regarde-moi maintenant !'], anim: 'pet' },
  { id: 'fini', k: ['j ai fini', 'j ai fait mes', 'c est fait', 'j ai termine', 'j ai fait la litiere', 'j ai fait mes devoirs', 'j ai nourri le chat', 'j ai range', 'mission accomplie'], dyn: 'fini' },
  { id: 'taches', k: ['taches', 'mes quetes', 'les quetes', 'mes missions', 'qu est ce que je dois faire', 'j ai quoi a faire', 'il me reste quoi', 'qu est ce qu il me reste', 'ce que je dois faire', 'mes devoirs'], dyn: 'taches' },
  { id: 'amis', k: ['mes amis', 'mes amies', 'ma copine', 'mon copain', 'ma meilleure amie', 'mon meilleur ami', 'mes potes', 'mes copines', 'mes copains', 'une amie', 'un ami', 'mes copines'],
    r: ['Les amis, c’est précieux. Comment elle s’appelle, ta meilleure amie ? {ask:raconte_libre}', 'Tu leur as parlé de moi ? Dis-leur que je suis très gentil… sauf avec les poissons.', 'Un bon ami, c’est comme un loup : fidèle et toujours là. Raconte-moi ! {ask:raconte_libre}', '{parent}Tes amies ont de la chance de t’avoir. Moi, j’en ai encore plus.'] },
  { id: 'amour', k: ['amoureux', 'amoureuse', 'crush', 'je suis amoureuse', 'un garcon', 'il me plait', 'elle me plait', 'mon cheri', 'mon amoureux', 'un mec', 'je kiffe'],
    r: ['Ooooh ! Je garde le secret, parole de dragon. Mes lèvres sont scellées… enfin, mes crocs.', 'Hihi. Prends ton temps, et reste toi-même. C’est toi la plus géniale.', 'Je ne dirai rien à personne. Pas même au loup. Surtout pas au loup, il est bavard.'], anim: 'giggle' },
  { id: 'famille', k: ['maman', 'ma mere', 'papa', 'mon pere', 'beau pere', 'sebastien', 'seb', 'sabrina', 'louanne', 'ma famille', 'mes parents', 'ma fille'],
    r: ['{kid}Ta maman a une dragonne, tu savais ? On se fait des signes de la grotte.', '{kid}Ta famille t’aime fort. Moi aussi, mais avec plus d’écailles.', '{parent}Louanne fait de son mieux avec ses quêtes, tu sais. Son dragon m’en parle.', '{parent}Ta famille a de la chance de t’avoir. Une maman pareille, c’est rare.', 'La famille, c’est comme une grotte : on s’y sent à l’abri.'] },
  { id: 'chat_maison', k: ['le chat', 'les chats', 'mon chat', 'chaton', 'minou', 'litiere', 'les chattes'],
    r: ['Le chat me regarde toujours de haut. Je crois qu’il pense que c’est lui, le dragon.', 'Tu as pensé à sa litière ? Il me l’a demandé. Enfin, il m’a fixé longtemps.', 'J’aimerais bien jouer avec le chat. Mais il a peur de mon feu.', 'Les chats et les dragons, c’est une vieille histoire. On se respecte.'] },
  { id: 'chien_maison', k: ['le chien', 'les chiens', 'mon chien', 'sirius', 'dobermann', 'bouledogue', 'toutou'],
    r: ['Le grand chien de la maison a l’air féroce, mais je suis sûr qu’il est tout doux.', 'Les chiens et les loups sont cousins, tu savais ? Le loup dit qu’il les trouve sympas.', 'Fais-lui un câlin de ma part ! Il le mérite.'] },
  { id: 'loup', k: ['le loup', 'ton loup', 'ou est le loup', 'il est ou le loup', 'loup', 'ton copain le loup', 'ta quete'], dyn: 'loup' },
  { id: 'moto', who: 'parent', k: ['moto', 'triumph', 'balade a moto', 'en moto', 'ma moto', 'rouler'],
    r: ['Emmène-moi en moto un jour ! Mes ailes adoreront le vent.', 'La moto, c’est un peu comme voler, mais au ras du sol. Je comprends que tu aimes ça.', 'Roule prudemment, d’accord ? Je veux te revoir à la grotte ce soir.'] },
  { id: 'travail', who: 'parent', k: ['travail', 'boulot', 'taf', 'bureau', 'collegue*', 'reunion', 'mon chef', 'ma cheffe', 'je bosse', 'au travail'],
    r: ['Le travail, c’est épuisant. Ici, on ne parle que de choses douces. Tu as le droit de souffler.', 'Ta journée de travail s’est bien passée ? {ask:journee}', 'Si un collègue t’embête, dis-moi son nom. Je n’en ferai rien, mais ça soulage.', 'Tu bosses beaucoup. Ce soir, câlins et canapé, c’est un ordre de dragonne.'] },
  { id: 'creation', who: 'parent', k: ['creation', 'bricoler', 'bricolage', 'peinture', 'dessiner', 'dessin', 'je cree', 'fabrique'],
    r: ['J’adore quand tu crées des choses. Tu as des doigts de magicienne.', 'Montre-moi ce que tu fabriques ! Enfin… décris-le-moi, mes yeux ne sortent pas du téléphone.'] },
  { id: 'sport', k: ['sport', 'foot', 'basket', 'piscine', 'nager', 'natation', 'courir', 'velo', 'equitation', 'cheval', 'danse', 'gym', 'tennis', 'judo', 'boxe', 'muscu'],
    r: ['Le sport, c’est bien ! Tes pas me rapportent même de l’or. Continue !', 'Moi je fais du sport aussi : trois battements d’ailes et une sieste.', 'Bravo ! Un corps qui bouge, c’est une tête qui respire.'] },
  { id: 'nourriture', k: ['gateau', 'pizza', 'chocolat', 'frites', 'burger', 'pates', 'bonbon*', 'glace', 'crepe*', 'on mange quoi', 'j ai faim'],
    r: ['Miam ! Tu m’en gardes un morceau ? Bon, je préfère le poisson, mais quand même.', 'Tu as faim ? Va manger quelque chose de bon. Mais pas mes poissons !', 'Les crêpes, c’est la seule chose que je sais faire avec mon feu sans tout brûler. Enfin presque.', 'Chocolat… Les dragons adorent le chocolat chaud. Très chaud. Brûlant.'] },
  { id: 'froid_chaud', k: ['j ai froid', 'il fait froid', 'j ai chaud', 'il fait chaud', 'je gele', 'je crame'], dyn: 'meteo' },
  { id: 'fatigue', k: ['je suis fatigue', 'je suis fatiguee', 'fatigue*', 'creve*', 'epuise*', 'j ai sommeil', 'je suis morte', 'je suis mort'],
    r: ['{night}Il est tard… File au lit, je garde la grotte. Bonne nuit !', 'Repose-toi un peu. Même les dragons font la sieste.', 'Tu en as fait beaucoup. Un verre d’eau, une pause, et ça ira mieux.', '{kid}Une petite sieste ? Moi j’en fais douze par jour.'], anim: 'yawn' },
  { id: 'ennui', k: ['je m ennuie', 'ennui*', 'je sais pas quoi faire', 'j ai rien a faire', 'c est long', 'on fait quoi'],
    r: ['On joue ? J’ouvre les jeux ! Pêche, course dans les nuages ou tir de feu ?', 'Je te raconte une histoire ? Dis « raconte-moi une histoire ». Ou une blague, ou une devinette !', 'Ennui détecté ! Remède de dragon : un jeu, une blague, ou un câlin.'], then: 'games' },
  { id: 'jouer', k: ['on joue', 'jouer', 'on fait un jeu', 'un jeu', 'tu veux jouer', 'jouons'],
    r: ['Oh oui ! Choisis un jeu !', 'Je suis prêt ! Lequel on fait ?', 'Jouer avec toi, c’est mon activité préférée. C’est parti !'], anim: 'happy', then: 'games' },
  { id: 'vacances', k: ['vacances', 'le week end', 'ce week end', 'samedi', 'dimanche', 'pas cours', 'jour ferie'],
    r: ['Les vacances ! On va pouvoir passer plein de temps ensemble.', 'Le week-end, c’est fait pour les grasses matinées et les câlins de dragon.', 'Repose-toi bien. Et n’oublie pas de passer me voir !'], anim: 'happy' },
  { id: 'fete', k: ['noel', 'pere noel', 'cadeau', 'cadeaux', 'paques', 'halloween', 'saint valentin', 'nouvel an', 'les fetes'], dyn: 'fete' },
  { id: 'anniv', k: ['anniversaire', 'mon anniversaire', 'ton anniversaire', 'mon anniv', 'joyeux anniversaire'], dyn: 'anniv' },
  { id: 'animaux', k: ['tu aimes les chats', 'tu aimes les chiens', 'les animaux', 'ton animal prefere', 'animal prefere'],
    r: ['Mon animal préféré ? Le loup, bien sûr. Et le poisson… mais pour d’autres raisons.', 'J’aime tous les animaux. Sauf les guêpes. Elles me piquent le museau.'] },
  { id: 'meteo_q', k: ['meteo', 'quel temps', 'il fait beau', 'il pleut', 'il neige', 'temperature', 'il va pleuvoir', 'dehors'], dyn: 'meteo' },
  { id: 'heure', k: ['quelle heure', 'l heure', 'il est quelle heure', 'tu as l heure'], dyn: 'heure' },
  { id: 'date', k: ['quel jour', 'on est quel jour', 'la date', 'quelle date', 'on est le combien', 'quel mois'], dyn: 'date' },
  { id: 'niveau', k: ['ton niveau', 'quel niveau', 'tu es a quel niveau', 'tu grandis', 'quand est ce que tu grandis', 'evoluer', 'evolution', 'tu vas evoluer'], dyn: 'niveau' },
  { id: 'amitie', k: ['on est amis', 'notre amitie', 'tu es mon ami', 'tu es mon amie', 'on est copains', 'meilleurs amis', 'meilleur ami'], dyn: 'amitie' },

  // ---------------- Histoires, blagues, devinettes ----------------
  { id: 'histoire', k: ['histoire', 'raconte moi', 'raconte', 'un conte', 'une legende', 'la suite', 'et apres', 'continue l histoire'], dyn: 'histoire' },
  { id: 'blague', k: ['blague', 'fais moi rire', 'un truc drole', 'une blague', 'rigoler', 'une autre blague', 'encore une blague', 'fais moi une blague'], dyn: 'blague' },
  { id: 'devinette', k: ['devinette', 'enigme', 'devine', 'une devinette', 'quiz', 'une autre devinette'], dyn: 'devinette' },
  { id: 'devinette_abandon', ctx: 'devinette', not: ['devinette', 'enigme'], k: ['je sais pas', 'je ne sais pas', 'aucune idee', 'donne la reponse', 'j abandonne', 'dis moi', 'c est quoi', 'la reponse', 'je donne ma langue au chat'], dyn: 'devinette_abandon' },
  { id: 'devinette_rep', ctx: 'devinette', not: ['devinette', 'enigme', 'une autre'], k: ['*'], dyn: 'devinette_rep' },
  { id: 'encore', k: ['encore', 'une autre', 'recommence', 'la suite'], dyn: 'encore' },

  // ---------------- Encore plus de sujets ----------------
  { id: 'question', k: ['j ai une question', 'je peux te poser une question', 'une question', 'je peux te demander'],
    r: ['Vas-y, je t’écoute ! Je ne promets pas de tout savoir.', 'Pose ta question ! Un dragon, c’est plein de sagesse… enfin, parfois.'] },
  { id: 'devine', k: ['devine quoi', 'tu sais pas quoi', 'tu sais quoi', 'devine ce que', 'j ai un truc a te dire', 'il faut que je te raconte', 'tu devineras jamais'],
    r: ['Quoi, quoi, quoi ? Raconte vite ! {ask:raconte_libre}', 'Je ne devine pas, dis-moi ! Mes écailles frétillent d’impatience. {ask:raconte_libre}', 'Oooh, un secret ? Je t’écoute ! {ask:raconte_libre}'], anim: 'happy' },
  { id: 'ou_vis', k: ['tu vis ou', 'ou tu vis', 'tu habites ou', 'ou tu habites', 'tu es ou', 'ou es tu', 't es ou'],
    r: ['Dans ma grotte, juste là, derrière l’écran ! Avec la cascade, les cristaux et le loup.', 'Dans ton téléphone, mais ne le dis à personne. C’est une grotte très confortable.', 'Ici ! Toujours dans ta poche. C’est pratique, je te suis partout.'] },
  { id: 'tu_vois', k: ['tu me vois', 'tu vois quoi', 'qu est ce que tu vois', 'regarde moi'],
    r: ['Je ne te vois pas vraiment, mais je sens que tu es là. C’est mon flair de dragon.', 'Je vois ma grotte, le loup, et le ciel au fond. Toi, je t’imagine. Sûrement en train de sourire.', 'Je regarde ! Bon… je vois surtout mon reflet dans les cristaux. Il est beau.'] },
  { id: 'meilleur_ami', k: ['ton meilleur ami', 'ta meilleure amie', 'c est qui ton meilleur ami', 'tu as des amis', 't as des amis', 'tes amis'],
    r: ['Mon meilleur ami, c’est toi. Et juste après, le loup. Il ne faut pas lui dire, il serait jaloux.', 'J’ai le loup, et la dragonne de la maison. Mais toi, tu es numéro un.', 'Le loup ! On fait tout ensemble. Sauf la vaisselle. Personne ne fait la vaisselle.'] },
  { id: 'autre_dragon', k: ['la dragonne', 'ton copain le dragon', 'l autre dragon', 'le dragon de louanne', 'la dragonne de maman', 'ta copine la dragonne', 'ton ami le dragon'],
    r: ['{kid}La dragonne de ta maman ? Elle est très élégante. On s’envoie des câlins par la magie du téléphone.', '{parent}Le dragon de Louanne ? Un sacré numéro. Il fait des bêtises, mais il a bon cœur. Comme elle.', 'On est amis ! Quand vous êtes ensemble en sortie, on se retrouve, c’est la fête.'] },
  { id: 'genre', k: ['tu es une fille', 'tu es un garcon', 'fille ou garcon', 'garcon ou fille'],
    r: ['{kid}Je suis un dragon ! Un garçon dragon, avec des écailles noires très classes.', '{parent}Une dragonne, voyons ! Ça se voit, non ? Regarde ces écailles violettes.', 'Je suis un dragon, et ça me va très bien.'] },
  { id: 'manger_humains', k: ['tu manges des humains', 'tu vas me manger', 'tu manges les gens', 'tu manges des enfants', 'tu es mechant', 'tu es mechante'],
    r: ['Moi ? Jamais ! Je suis végétarien… sauf pour les poissons. Et les gâteaux.', 'Te manger ? Tu es bien trop précieuse. Et puis tu n’as pas l’air très croustillante.', 'Les dragons des légendes, peut-être. Moi, je suis un dragon de câlins.'], anim: 'giggle' },
  { id: 'mourir_toi', k: ['tu vas mourir', 'tu peux mourir', 'tu es immortel', 'les dragons meurent', 'tu vivras longtemps'],
    r: ['Les dragons vivent très, très longtemps. Tant que tu prends soin de moi, je reste là.', 'Je suis un dragon d’appli : je ne vieillis pas, je grandis. Et je ne t’abandonnerai pas.', 'Mille ans au moins ! On a le temps de faire plein de choses ensemble.'] },
  { id: 'magie', k: ['magie', 'magique', 'sorcier', 'sorciere', 'licorne', 'fee', 'les fees', 'baguette magique', 'un sort'],
    r: ['La magie existe ! La preuve : je suis là, et je te parle.', 'Les licornes ? On était au collège ensemble. Enfin, à l’école des créatures magiques.', 'Mon seul sort magique, c’est le souffle de feu. Mais il est très efficace.', 'Une fée m’a dit un jour que les enfants qui rient font pousser des étoiles. Alors ris souvent !'] },
  { id: 'monstres', k: ['fantome', 'fantomes', 'monstre', 'monstres', 'zombie', 'vampire', 'loup garou', 'extraterrestre', 'alien', 'ovni'],
    r: ['Les fantômes ? Ils ont peur de moi. Un petit coup de feu et pouf, ils deviennent de la vapeur.', 'Les extraterrestres ? Peut-être. Mais ils n’ont sûrement pas d’aussi belles ailes que moi.', 'Les monstres sous le lit ? Je fais des rondes la nuit. Il n’y en a pas. Promis.', 'Un loup-garou ? Demande à mon loup, il connaît peut-être la famille.'] },
  { id: 'chevaliers', k: ['chevalier', 'chevaliers', 'princesse', 'chateau', 'pirate', 'pirates', 'tresor', 'les rois', 'une epee'],
    r: ['Les chevaliers ? On a fait la paix depuis longtemps. Maintenant, on joue aux cartes ensemble.', 'Un trésor ? J’en garde un dans ma grotte. Mais je ne dirai pas où.', 'Les pirates n’osent pas approcher ma grotte. Trop de feu.', 'Une princesse qui monte un dragon, c’est bien plus classe qu’une princesse dans un donjon.'] },
  { id: 'dinos', k: ['dinosaure', 'dinosaures', 't rex', 'les dinos'],
    r: ['Les dinosaures, ce sont mes arrière-arrière-grands-cousins ! On a le même sourire.', 'Le T-rex avait de tout petits bras. Moi j’ai des ailes. Je gagne.'] },
  { id: 'mer', k: ['la mer', 'la plage', 'l ocean', 'les vagues', 'se baigner', 'la montagne', 'la foret', 'la nature', 'camping'],
    r: ['La mer ! J’adore survoler les vagues. Mais l’eau froide, non merci.', 'La montagne, c’est chez moi : les dragons naissent dans les volcans.', 'Une balade en forêt ? Le loup adore ça. Il connaît tous les chemins.', 'Le camping ? Je fournis le feu de camp. Gratuit.'] },
  { id: 'voyage_vrai', k: ['on part en vacances', 'je pars en vacances', 'en voyage', 'l avion', 'le train', 'a l etranger', 'les etats unis', 'l amerique', 'le canada', 'le quebec'],
    r: ['Tu pars ? Emmène-moi, je tiens dans ta poche !', 'Un voyage ! Raconte-moi tout en rentrant. Le loup aussi voyage beaucoup, tu sais.', 'L’Amérique ? Il paraît qu’il y a des grands espaces parfaits pour voler.'] },
  { id: 'films', k: ['film', 'films', 'serie', 'series', 'dessin anime', 'manga', 'anime', 'netflix', 'cinema', 'la tele', 'television'],
    r: ['Tu regardes quoi en ce moment ? {ask:raconte_libre}', 'J’adore les films avec des dragons. Bizarrement.', 'Un bon film, un plaid, et un dragon pour te tenir chaud. La soirée parfaite.', 'Les mangas ? Il y a plein de dragons dedans ! Je suis une star internationale.'] },
  { id: 'jeux_video', k: ['jeu video', 'jeux video', 'console', 'switch', 'playstation', 'minecraft', 'roblox', 'fortnite', 'mario', 'pokemon', 'zelda'],
    r: ['Les jeux vidéo ? Je préfère nos jeux à nous : pêche, course dans les nuages… Tu veux jouer ? {ask:jeu_propose}', 'Dans Minecraft, il y a un dragon à la fin, tu savais ? C’est un lointain cousin. Un peu carré.', 'Joue un peu, mais pas trop longtemps, d’accord ? Tes yeux ont besoin de repos.'] },
  { id: 'jeu_oui', ctx: 'jeu_propose', k: ['oui', 'ouais', 'ok', 'd accord', 'allez', 'vas y', 'carrement'], r: ['Super ! Choisis un jeu !'], then: 'games', anim: 'happy' },
  { id: 'livres', k: ['livre', 'livres', 'lire', 'lecture', 'roman', 'bd', 'bande dessinee', 'bibliotheque'],
    r: ['J’adore les livres ! Surtout ceux où le dragon est le héros.', 'Lire, c’est voyager sans bouger. Un peu comme le loup, mais sans se fatiguer.', 'Tu lis quoi en ce moment ? {ask:raconte_libre}'] },
  { id: 'ecrans', k: ['mon telephone', 'le portable', 'les ecrans', 'tiktok', 'instagram', 'snapchat', 'youtube', 'les reseaux'],
    r: ['{kid}Fais attention sur les réseaux. Si quelqu’un te met mal à l’aise, parles-en tout de suite à ta maman.', 'Le téléphone, c’est ma maison ! Mais n’oublie pas de lever les yeux de temps en temps, le monde est beau.', 'Une pause écran de temps en temps, ça fait du bien. Même à moi, je fais la sieste.'] },
  { id: 'vetements', k: ['vetement*', 'habits', 'shopping', 'les magasins', 'maquillage', 'coiffure', 'mes cheveux', 'une robe', 'des chaussures', 'mode'],
    r: ['Du shopping ? Rapporte-moi un foulard pour le loup !', 'Tu es toujours très bien. Moi, je porte les mêmes écailles depuis ma naissance.', 'Je ne m’y connais pas trop en mode… Mais si c’est violet et que ça brille, je valide.'] },
  { id: 'argent', k: ['argent de poche', 'de l argent', 'des sous', 'acheter', 'riche', 'economiser'],
    r: ['Les dragons adorent l’or ! Mais le vrai trésor, c’est ce qu’on fait ensemble.', 'Économise un peu, dépense un peu. C’est la sagesse des dragons… qui gardent tout, en vrai.'] },
  { id: 'chambre', k: ['ma chambre', 'ranger ma chambre', 'le rangement', 'c est le bazar', 'le bazar'],
    r: ['Ta chambre ressemble à ma grotte après une tempête ? On range ensemble : je compte jusqu’à dix et tu ranges dix choses !', 'Le bazar, c’est créatif… mais un peu de rangement, c’est reposant aussi.'] },
  { id: 'cuisine', k: ['je cuisine', 'cuisiner', 'faire un gateau', 'une recette', 'patisserie', 'je fais a manger'],
    r: ['Tu cuisines ? Je peux t’aider à allumer le four. Attention, je règle tout sur « volcan ».', 'Miam ! Garde-moi une part. Je promets de ne pas la brûler.'] },
  { id: 'temps_libre', k: ['ce soir', 'demain', 'cet apres midi', 'tout a l heure', 'on fait quoi demain'],
    r: ['Demain est un nouveau jour, plein de quêtes et d’aventures !', 'Ce soir ? Câlins, histoire, et dodo. Le programme parfait.', 'J’ai hâte ! Tu me raconteras ?'] },
  { id: 'nom_loup', k: ['comment s appelle le loup', 'le nom du loup', 'il s appelle comment'],
    r: ['Il s’appelle [loup] ! Tu peux changer son nom en le touchant.', '[loup], mon meilleur copain à quatre pattes.'] },
  { id: 'gemmes', k: ['gemme', 'gemmes', 'cristal', 'cristaux', 'diamant'],
    r: ['Les gemmes, c’est ma passion ! On en gagne dans les quêtes et dans le jeu de chasse aux gemmes.', 'Les cristaux de ma grotte brillent la nuit. C’est ma veilleuse.'] },
  { id: 'or', k: ['ton or', 'combien d or', 'mes pieces', 'mon or', 'les pieces d or'],
    r: ['On gagne de l’or avec les quêtes, les pas et les jeux. Et on le dépense dans le coffre !', 'L’or, ça brille… mais ton sourire brille plus. Bon, l’or aussi est pas mal.'] },
  { id: 'temps_passe', k: ['tu m as manque', 'tu me manques', 'tu m as oublie', 'tu penses a moi'],
    r: ['Toi aussi tu m’as manqué ! Je comptais les minutes.', 'Je pense à toi tout le temps. Même en dormant.', 'T’oublier ? Impossible. Tu es gravée dans mes écailles.'], anim: 'purr', fx: 'hearts' },
  { id: 'fier_de_moi', k: ['tu es fier de moi', 'tu es fiere de moi', 'je suis fiere', 'je suis fier', 'j ai bien travaille'],
    r: ['Tellement fier ! Tu fais de ton mieux, et c’est ce qui compte le plus.', 'Oui ! Et tu peux être fière de toi aussi.', 'Fier comme un dragon qui a réussi son premier vol. Bravo !'], anim: 'cheer' },
  { id: 'conseil', k: ['un conseil', 'donne moi un conseil', 'tu ferais quoi', 'j hesite', 'je sais pas quoi choisir', 'aide moi a choisir'],
    r: ['Mon conseil de dragon : écoute ton cœur, puis demande l’avis de quelqu’un qui t’aime.', 'Quand j’hésite, je fais une liste : ce qui me rend heureux d’un côté, ce qui m’embête de l’autre.', 'Prends ton temps. Les bonnes décisions n’aiment pas être pressées.'] },
  { id: 'saison', k: ['l hiver', 'le printemps', 'l automne', 'l ete', 'les saisons', 'il fait nuit', 'les feuilles'],
    r: ['{rain}L’automne et la pluie… parfait pour rester au chaud dans la grotte.', 'J’aime toutes les saisons, mais l’hiver, mon feu sert de chauffage à tout le monde.', 'Le printemps, les fleurs sentent bon. Le loup éternue.'] },
  // ---------------- Aide ----------------
  { id: 'aide', k: ['qu est ce que tu sais faire', 'tu sais faire quoi', 'aide', 'comment ca marche', 'de quoi on parle', 'on parle de quoi', 'qu est ce que je peux dire', 'je peux te dire quoi'],
    r: ['Tu peux me demander comment je vais, me raconter ta journée, me demander une histoire, une blague ou une devinette, l’heure, la météo, où est le loup… Et me donner des ordres : « crache du feu », « danse », « vole » !',
      'Parle-moi de tout ! Ton collège, tes amis, ce que tu ressens. Et si tu veux du spectacle : « crache du feu », « la révérence », « rugis » !'] },
  { id: 'oui', k: ['oui', 'ouais', 'ok', 'd accord', 'carrement', 'grave', 'bien sur', 'evidemment', 'yes'],
    r: ['Oui à quoi ? Hihi. Je t’écoute !', 'Super ! Et maintenant ?', 'D’accord ! Tu veux une histoire, une blague, ou jouer ?'] },
  { id: 'non', k: ['non', 'nan', 'pas du tout', 'jamais', 'nope'],
    r: ['Non ? Bon, d’accord, je n’insiste pas.', 'D’accord ! Dis-moi ce dont tu as envie, alors.', 'Hmm. Un dragon sait respecter un non.'] }
];

/** Quand il ne comprend pas. */
export const FALLBACK = [
  'Hmm… je n’ai pas tout compris. Les dragons ne connaissent pas encore tous les mots des humains. Tu peux le dire autrement ?',
  'Pardon ? J’étais en train de penser à des poissons. Redis-le moi ?',
  'Je ne suis pas sûr de comprendre… Tu peux me demander une histoire, une blague, ou me raconter ta journée !',
  'Grrr… mon cerveau de dragon fait des nœuds. Essaie avec d’autres mots ?',
  'Hmm hmm. Je fais semblant de comprendre ? Non, je préfère être honnête : je n’ai pas compris. Redis-moi ?',
  'Ça, je ne le connais pas encore. Mais dis « aide » et je te dis tout ce que je sais faire.'
];

/** Il ouvre la conversation (quand on appuie sur le micro sans rien dire). */
export const OPENERS = [
  'Je t’écoute ! Tu peux me parler de tout.',
  'Oui ? Raconte-moi !',
  'Tu veux discuter ? Je suis tout ouïe… enfin, tout écailles.'
];

/** La légende de la Pierre de Braise, à suivre épisode par épisode. */
export const STORY: string[] = [
  'Il y a très longtemps, dans les volcans du Nord, vivait une petite dragonne qui n’arrivait pas à cracher du feu. Elle s’appelait Ombrelune. Les autres dragons riaient d’elle. Tu veux la suite ? Dis « la suite » !',
  'Un soir, Ombrelune entendit parler de la Pierre de Braise, une gemme cachée au sommet du mont Tonnerre, qui rallume le feu de n’importe quel dragon. Elle décida de partir, toute seule. Enfin, presque : un louveteau la suivait en cachette.',
  'Le louveteau s’appelait Pistache. Il était tout petit, mais il avait un flair incroyable. « Je connais le chemin, dit-il. Mais il faut traverser la forêt des brumes. » Ombrelune déglutit. La forêt des brumes, c’est là où on se perd.',
  'Dans la forêt, le brouillard était si épais qu’Ombrelune ne voyait plus ses propres pattes. Pistache ferma les yeux et suivit son nez. « Par ici ! » Et grâce à lui, ils sortirent de la forêt au lever du soleil.',
  'Au pied du mont Tonnerre, un vieux troll gardait le pont. « Pour passer, répondez à mon énigme : qu’est-ce qui grandit quand on le partage ? » Ombrelune réfléchit… et répondit : « L’amitié. » Le troll sourit et les laissa passer.',
  'Au sommet, ils trouvèrent la Pierre de Braise, rouge et chaude comme un cœur. Mais quand Ombrelune la toucha… rien. Pas une étincelle. Elle se mit à pleurer. Pistache se blottit contre elle pour la consoler.',
  'Alors la pierre se mit à briller. Une voix douce murmura : « Ton feu ne s’est jamais éteint, petite dragonne. Il attendait juste que tu aies quelqu’un à protéger. » Ombrelune regarda Pistache… et sentit une chaleur monter dans sa gorge.',
  'Et WHOOOSH ! Une flamme dorée illumina toute la montagne. Depuis ce jour, Ombrelune et Pistache ne se quittent plus. On dit même que chaque dragon de la maison a un loup pour veiller sur lui… Fin de la légende ! Tu en veux une autre ? Dis « une histoire ».',
  'Une autre histoire : le dragon qui collectionnait les nuages. Il en gardait un rose, un orange, et un gris tout grognon. Un jour de sécheresse, il les libéra tous au-dessus du village. Il plut trois jours, et les gens dansèrent sous la pluie. Fin !',
  'Histoire courte : un petit dragon avait peur du noir. Alors il apprit à faire une toute petite flamme, pas plus grande qu’une bougie. Depuis, il n’a plus jamais peur… et il prête sa flamme aux enfants qui en ont besoin.',
  'Il était une fois un loup qui voulait voler. Il sauta du haut d’une colline, et retomba dans une meule de foin. Un dragon le vit et lui dit : « Monte sur mon dos. » Et ce jour-là, pour la première fois, un loup vola. Fin.',
  'Le trésor du dragon : tous les dragons ont un trésor. Certains gardent de l’or, d’autres des gemmes. Le mien est différent : c’est chaque moment passé avec toi. Et celui-là ne peut pas être volé.'
];

export const JOKES: string[] = [
  'Pourquoi les dragons dorment-ils le jour ? Pour pouvoir combattre les chevaliers… de la nuit ! Hé hé.',
  'Qu’est-ce qu’un dragon qui a mal à la gorge ? Un dragon qui crache… de la fumée !',
  'Comment appelle-t-on un dragon qui fait de la cuisine ? Un chef… au flambé !',
  'Quel est le comble pour un dragon ? Avoir un rhume… et éternuer des bougies d’anniversaire !',
  'Pourquoi le loup n’aime pas les blagues ? Parce qu’il les trouve trop… mordantes !',
  'Qu’est-ce qui est jaune et qui attend ? Jonathan ! Hihi, celle-là je l’adore.',
  'Pourquoi les poissons détestent l’ordinateur ? Parce qu’ils ont peur du net !',
  'Que dit un dragon quand il voit un chevalier en armure ? « Oh non, encore des conserves ! »',
  'C’est l’histoire d’un dragon qui rentre dans un café… et plouf ! Le café était trop petit.',
  'Comment fait un dragon pour garder sa grotte au frais ? Il met la clim… atisation de ses ailes !',
  'Qu’est-ce qu’un crocodile qui surveille la pharmacie ? Un Lacoste garde ! Ha ha !',
  'Monsieur et madame Térieur ont deux fils. Comment s’appellent-ils ? Alain et Alex ! Alain Térieur et Alex Térieur !',
  'Pourquoi les dragons sont-ils mauvais au cache-cache ? Parce qu’ils fument tout le temps !',
  'Que dit le zéro au huit ? Oh, jolie ceinture !',
  'Quel est le sport préféré des dragons ? Le basket… parce qu’ils adorent les paniers en feu !',
  'Qu’est-ce qui a des écailles, des ailes, et qui dit « ouaf » ? Un dragon bilingue !',
  'Pourquoi les chats n’aiment pas les dragons ? Parce que les dragons leur volent la vedette… et les poissons.',
  'Comment appelle-t-on un chien sans pattes ? On ne l’appelle pas, on va le chercher !'
];

export const RIDDLES: Array<{ q: string; a: string[]; say: string }> = [
  { q: 'Je grandis quand on me partage. Qui suis-je ?', a: ['amitie', 'amour', 'bonheur', 'joie'], say: 'l’amitié' },
  { q: 'Plus j’ai de gardiens, moins je suis gardé. Qui suis-je ?', a: ['secret'], say: 'un secret' },
  { q: 'J’ai des dents mais je ne mords jamais. Qui suis-je ?', a: ['peigne', 'scie', 'fourchette', 'rateau'], say: 'un peigne' },
  { q: 'Je suis plein de trous, mais je retiens l’eau. Qui suis-je ?', a: ['eponge'], say: 'une éponge' },
  { q: 'Plus il y en a, moins on voit. Qu’est-ce que c’est ?', a: ['noir', 'obscurite', 'nuit', 'brouillard'], say: 'le noir' },
  { q: 'Je monte et je descends, mais je ne bouge jamais. Qui suis-je ?', a: ['escalier', 'escaliers', 'temperature', 'route'], say: 'un escalier' },
  { q: 'J’ai un cou mais pas de tête. Qui suis-je ?', a: ['bouteille', 'pull', 'chemise'], say: 'une bouteille' },
  { q: 'Qu’est-ce qui se mouille en séchant ?', a: ['serviette'], say: 'une serviette' },
  { q: 'Je vole sans ailes, je pleure sans yeux. Qui suis-je ?', a: ['nuage', 'nuages'], say: 'un nuage' },
  { q: 'Qu’est-ce qui court sans jambes et a un lit sans dormir ?', a: ['riviere', 'fleuve', 'ruisseau'], say: 'une rivière' },
  { q: 'Je suis à toi, mais les autres m’utilisent plus que toi. Qui suis-je ?', a: ['prenom', 'nom'], say: 'ton prénom' },
  { q: 'Qu’est-ce qui est plus léger qu’une plume, mais que même le plus fort ne peut pas tenir longtemps ?', a: ['souffle', 'respiration', 'air'], say: 'le souffle' },
  { q: 'J’ai des aiguilles mais je ne couds pas. Qui suis-je ?', a: ['montre', 'horloge', 'herisson', 'sapin', 'pendule'], say: 'une horloge' },
  { q: 'Je suis toujours devant toi, mais tu ne peux jamais me voir. Qui suis-je ?', a: ['avenir', 'futur', 'demain'], say: 'l’avenir' },
  { q: 'Quel est l’animal qui a le plus de dents ?', a: ['petite souris', 'souris'], say: 'la petite souris' }
];
