// Deuxième banque de répliques : envies, activités, réactions, vie quotidienne, émotions, petits savoirs.
// Même format que DialogueData.ts (mots-clés sans accents, étiquettes {kid} {parent} {ask:...}, [nom] [loup] [prenom]).
import type { IntentDef } from './DialogueData.js';

export const MORE_INTENTS: IntentDef[] = [
  // ---------------- Ses envies ----------------
  { id: 'envie', k: ['tu veux faire quoi', 'qu est ce que tu veux faire', 'tu voudrais faire quoi', 'tu as envie de faire quoi', 't as envie de faire quoi', 'tu as envie de quoi', 't as envie de quoi', 'envie de quoi', 'on fait quoi', 'qu est ce qu on fait', 'tu veux qu on fasse quoi', 'qu est ce que tu aimerais faire', 'tu aimerais faire quoi', 'qu est ce qui te ferait plaisir', 'on fait quoi aujourd hui', 'qu est ce que tu veux', 'tu veux quoi', 'de quoi tu as envie', 'qu est ce qu on pourrait faire', 'on pourrait faire quoi', 'tu proposes quoi', 'une idee', 'tu as une idee'], dyn: 'envie' },
  { id: 'aime_faire', k: ['qu est ce que tu aimes faire', 'tu aimes faire quoi', 'tes activites', 'ton activite preferee', 'tu fais quoi de tes journees', 'tu fais quoi quand je suis pas la', 'tu fais quoi quand je ne suis pas la'],
    r: ['J’aime voler, faire des tours, pêcher avec le loup… et surtout parler avec toi.', 'Quand tu n’es pas là ? Je dors, je compte mes écailles, et je regarde la porte en t’attendant.', 'Je m’entraîne à cracher du feu, je joue avec le loup, et je fais des siestes. Beaucoup de siestes.', 'Mon activité préférée, c’est quand tu ouvres l’appli. Juste après, la pêche.'] },
  { id: 'sortir', k: ['tu veux sortir', 'on sort', 'on va se promener', 'tu veux te promener', 'on va dehors', 'une balade', 'une promenade', 'tu viens avec moi', 'je t emmene', 'viens avec moi'],
    r: ['Oh oui ! Mets-moi dans ta poche. Et marche : chaque pas me rapporte de l’or !', 'Une balade ! Je ne peux pas sortir du téléphone, mais je compte tes pas. Allez, on bouge !', 'Je viens ! Enfin, dans ta poche. Et si vous êtes plusieurs, coche « Sortie en famille » : nos dragons se retrouvent.'], anim: 'happy' },
  { id: 'cache_cache', k: ['cache cache', 'on joue a cache cache', 'on fait une course', 'on fait la course', 'chat perche', 'un loup garou', 'on joue a un jeu', 'a quoi on joue', 'on joue a quoi'],
    r: ['Cache-cache ? Je suis nul, ma queue dépasse toujours. Viens plutôt jouer à la pêche ou à la course dans les nuages !', 'Une course ! Dans les nuages, je suis imbattable. Enfin presque. On y va ?', 'J’ai plein de jeux ! Choisis.'], then: 'games', anim: 'happy' },
  { id: 'peche', k: ['peche', 'pecher', 'on va pecher', 'une partie de peche', 'aller a la peche', 'des poissons'],
    r: ['La pêche ! Mon jeu préféré. Le loup prépare déjà la canne.', 'On va pêcher au lac ? Les poissons dorés n’ont qu’à bien se tenir !'], then: 'games', anim: 'happy' },

  // ---------------- Il parle, pose des questions ----------------
  { id: 'parle_moi', k: ['parle moi', 'dis moi quelque chose', 'dis moi un truc', 'raconte moi quelque chose', 'raconte moi un truc', 'dis quelque chose', 'parle', 'je t ecoute', 'vas y parle', 'dis moi', 'quoi de beau'], dyn: 'pensee' },
  { id: 'pose_question', k: ['pose moi une question', 'pose moi des questions', 'demande moi quelque chose', 'interroge moi', 'une question pour moi', 'tu as une question'], dyn: 'question_pour_toi' },
  { id: 'fun_fact', k: ['apprends moi quelque chose', 'un truc que je sais pas', 'une anecdote', 'tu savais que', 'le savais tu', 'un fait', 'culture', 'apprends moi un truc'], dyn: 'savoir' },
  { id: 'mes_gouts', k: ['qu est ce que j aime', 'tu sais ce que j aime', 'tu te souviens de ce que j aime', 'mes gouts', 'qu est ce que je deteste', 'tu te souviens', 'tu te rappelles'], dyn: 'mes_gouts' },

  // ---------------- Ses humeurs à lui ----------------
  { id: 'humeur_toi', k: ['tu es triste', 't es triste', 'tu es content', 'tu es contente', 't es content', 'tu es de bonne humeur', 'tu es de mauvaise humeur', 'tu es en colere', 't es en colere', 'tu es heureux', 'tu es heureuse', 'tu es bien', 'tu te sens bien', 'tu vas mieux', 'tu es seul', 'tu es seule'], dyn: 'humeur_toi' },
  { id: 'journee_toi', k: ['tu as passe une bonne journee', 'ta journee etait bien', 'bonne journee toi', 'tu as fait quoi de beau', 'tu as fait quoi pendant que j etais pas la', 'tu as fait quoi sans moi'], dyn: 'ma_journee' },
  { id: 'boude', k: ['tu boudes', 'tu m en veux', 'tu es fache', 'tu es fachee', 't es fache', 'tu fais la tete', 'tu fais la gueule'],
    r: ['Moi, bouder ? Jamais ! Enfin… trente secondes, maximum.', 'Je ne t’en veux pas du tout. Viens, on se fait un câlin.', 'Je faisais semblant ! Un dragon ne boude jamais longtemps.'], anim: 'purr' },
  { id: 'ennui_toi', k: ['tu t ennuies', 't t ennuies', 'tu t ennuyais', 'tu t ennuies pas', 'tu t es ennuye'],
    r: ['Un peu, quand tu n’es pas là. Mais là, maintenant, pas du tout !', 'Je m’ennuyais… jusqu’à ce que tu arrives. On fait un truc ?', 'Le loup essaie de me distraire, mais rien ne vaut toi.'] },
  { id: 'dormi_toi', k: ['tu as bien dormi', 't as bien dormi', 'bien dormi toi', 'tu as fait un cauchemar', 'ta nuit'],
    r: ['Très bien ! J’ai rêvé que je volais au-dessus d’une mer de nuages roses.', 'Comme un loir… enfin, comme un dragon. J’ai ronflé un peu, le loup s’est plaint.', 'J’ai rêvé de toi ! On pêchait un poisson géant. Il nous a éclaboussés.', 'Bof, le loup m’a réveillé deux fois en chassant des papillons imaginaires.'] },
  { id: 'froid_toi', k: ['tu as froid', 't as froid'], r: ['Froid ? Jamais ! J’ai un volcan dans le ventre.', 'Moi, froid ? Je suis un radiateur à écailles !'] },
  { id: 'chaud_toi', k: ['tu as chaud', 't as chaud'], r: ['Chaud ? Toujours un peu. C’est le métier de dragon.', '{hot}Un peu, oui ! Même les dragons trouvent qu’il fait chaud aujourd’hui.', 'J’ai toujours chaud, c’est normal : j’ai une braise dans la gorge.'] },
  { id: 'soif_toi', k: ['tu as soif', 't as soif', 'tu veux boire'], r: ['Soif ? Un peu… un bol d’eau tiède, s’il te plaît. Pas froide !', 'Toujours ! Cracher du feu, ça donne soif.'] },
  { id: 'trop_devoirs', k: ['trop de devoirs', 'plein de devoirs', 'beaucoup de devoirs', 'des devoirs a faire', 'j ai des devoirs', 'encore des devoirs', 'j ai devoirs'],
    r: ['Courage ! Commence par le plus court, ça donne de l’élan. Et une petite pause toutes les demi-heures.', 'Beaucoup de devoirs ? Un par un, comme les écailles d’un dragon : on les range une à une.', 'Je reste à côté de toi, en silence. Enfin, presque. Tu vas y arriver.'] },
  { id: 'mal_dormi', prio: 30, k: ['j ai mal dormi', 'mal dormi', 'j ai pas dormi', 'je n ai pas dormi', 'nuit blanche', 'j ai pas assez dormi', 'insomnie'],
    r: ['Oh… Ce soir, couche-toi un peu plus tôt. Et aujourd’hui, vas-y doucement.', 'Aïe. Un grand verre d’eau, un peu de lumière, et une sieste si tu peux.', 'Les nuits difficiles, ça arrive. Ce soir, je ferai une garde spéciale pour que tu dormes bien.'] },

  // ---------------- Petits mots doux ----------------
  { id: 'mots_doux', k: ['mon cheri', 'ma cherie', 'mon bebe', 'mon coeur', 'ma puce', 'mon amour', 'mon tresor', 'mon poussin', 'ma biche', 'mon lapin', 'mon chou', 'mon petit dragon', 'ma petite dragonne', 'mon grand', 'ma belle', 'mon beau', 'mon pote', 'mon gros', 'mon dragon', 'ma dragonne', 'mon bichon', 'mon doudou'],
    r: ['Oui, c’est moi ! Tu m’appelles comme ça et je fonds… enfin, je chauffe.', 'Mmh, j’adore quand tu m’appelles comme ça.', 'Présent ! Toujours là pour toi.', 'Tu as dit le mot magique, mes écailles brillent !', 'Oui, ma personne préférée ?'], anim: 'purr' },
  { id: 'tu_es_la', k: ['tu es la', 't es la', 'il y a quelqu un', 'y a quelqu un', 'ho ho', 'allo', 'tu m entends', 'tu es reveille', 'tu es reveillee', 'hello hello'],
    r: ['Je suis là ! Toujours là.', 'Présent ! Je ne bouge pas de ma grotte.', 'Oui, oui, je t’entends. Je faisais semblant de dormir.'] },
  { id: 'attends', k: ['attends moi', 'attends', 'deux minutes', 'une minute', 'je reviens', 'je reviens tout de suite', 'bouge pas', 'pause'],
    r: ['D’accord, je t’attends ici. Je ne bouge pas une écaille.', 'Je compte jusqu’à mille. Un… deux… Reviens vite !', 'Pas de souci, je garde ta place.'], then: 'end' },
  { id: 'tranquille', k: ['tais toi', 'laisse moi tranquille', 'laisse moi', 'pas maintenant', 'je suis occupee', 'je suis occupe', 'plus tard', 'chut', 'silence', 'arrete de parler', 'tais toi s il te plait'],
    r: ['D’accord, je me fais tout petit. Reviens quand tu veux.', 'Compris ! Je fais la sieste en attendant.', 'Chut… je ne dis plus rien. Enfin, presque.'], then: 'end' },

  // ---------------- Réactions courtes ----------------
  { id: 'reaction_wow', k: ['waouh', 'wow', 'whaou', 'ouah', 'trop bien', 'genial', 'super', 'top', 'trop cool', 'incroyable', 'g nial', 'excellent', 'parfait', 'trop fort', 'c est cool', 'c est genial', 'c est super', 'stylé', 'style', 'trop stylé'],
    r: ['Hihi, content que ça te plaise !', 'Je sais, je sais. Je suis un dragon impressionnant.', 'Trop bien, hein ? On recommence quand tu veux !', 'Waouh toi-même !'], anim: 'happy' },
  { id: 'reaction_bof', k: ['bof', 'mouais', 'bof bof', 'pas fou', 'c est nul', 'nul', 'pas terrible', 'mouai', 'boarf', 'c est pas drole', 'pas drole'],
    r: ['Hmm… pas convaincue ? Je ferai mieux la prochaine fois.', 'D’accord, j’ai compris, c’était pas mon meilleur moment.', 'Oups. Tu veux autre chose ? Une histoire, un jeu, une devinette ?'] },
  { id: 'reaction_ah', k: ['ah bon', 'ah oui', 'vraiment', 'c est vrai', 'serieux', 'serieusement', 'sans blague', 'non mais', 'pour de vrai', 'tu rigoles', 'c est pas vrai', 'je te crois pas', 'menteur', 'menteuse', 'n importe quoi'],
    r: ['Parole de dragon ! Croix de bois, croix de feu.', 'Enfin… peut-être que j’exagère un tout petit peu.', 'Puisque je te le dis ! Bon, demande au loup si tu ne me crois pas.', 'Hihi. Un dragon n’exagère jamais. Presque jamais.'] },
  { id: 'qui_quoi', k: ['c est qui', 'qui ca', 'qui c est', 'c est quoi', 'quoi', 'hein', 'pardon quoi', 'comment ca', 'de quoi'],
    r: ['Qui ça ? Quoi ça ? Raconte-moi, je suis curieux ! {ask:raconte_libre}', 'Hein ? Je me suis perdu. Tu peux redire ?', 'De quoi on parle ? Explique-moi ! {ask:raconte_libre}'] },
  { id: 'peut_etre', k: ['peut etre', 'on verra', 'je verrai', 'je vais reflechir', 'je sais pas trop', 'pourquoi pas'],
    r: ['D’accord, réfléchis. Moi je reste là.', 'On verra, oui. Les meilleures idées arrivent en mangeant un poisson.', 'Pas de pression ! Tu me diras.'] },
  { id: 'je_sais_pas', k: ['je sais pas', 'je ne sais pas', 'aucune idee', 'chais pas', 'j en sais rien', 'je sais plus', 'je ne sais plus'],
    r: ['Ce n’est pas grave de ne pas savoir. Moi non plus, je ne sais pas plein de choses.', 'Pas de souci ! On cherche ensemble ?', 'Hmm… alors on décide au hasard : une blague, une histoire, ou un jeu ?'] },
  { id: 'felicitations', k: ['bravo', 'felicitations', 'bien joue', 'bien joue toi', 'bon travail', 'champion', 'trop fort toi', 'tu as reussi'],
    r: ['Merci ! J’ai beaucoup travaillé. Surtout la sieste.', 'Hihi, merci ! C’est grâce à toi que je progresse.', 'Bravo à nous deux, alors !'], anim: 'cheer' },
  { id: 'voeux', k: ['bonne annee', 'joyeux noel', 'joyeuses paques', 'joyeux halloween', 'bonne saint valentin', 'bonnes fetes', 'bon week end', 'bonnes vacances', 'bonne journee', 'bonne soiree', 'bon appetit', 'joyeux anniversaire'],
    r: ['Merci, à toi aussi ! Plein de bonheur et de poissons grillés.', 'À toi aussi ! Tu es la meilleure.', 'Merci ! Je te souhaite la même chose, en double.'], anim: 'happy' },

  // ---------------- Commandes du quotidien ----------------
  { id: 'va_dormir', k: ['va dormir', 'va te coucher', 'au dodo', 'fais dodo', 'il est l heure de dormir', 'va au lit', 'fais une sieste', 'repose toi'],
    r: ['D’accord… bonne nuit. Enfin, bonne sieste. Zzz…', 'Oh, déjà ? Bon, d’accord. Tu me réveilles plus tard ?'], anim: 'yawn', then: 'sleep' },
  { id: 'reveille', k: ['reveille toi', 'debout', 'leve toi', 'allez debout', 'on se reveille'],
    r: ['Hein ? Quoi ? Je ne dormais pas ! Je réfléchissais les yeux fermés.', 'Je suis réveillé ! Bonjour, bonjour !', 'Mmh… encore cinq minutes… Bon, d’accord, je me lève.'], anim: 'stretch' },
  { id: 'voyage_loup', k: ['envoie le loup', 'envoie le loup en quete', 'le loup en quete', 'une quete pour le loup', 'le loup peut partir', 'fais partir le loup', 'le loup en voyage'],
    r: ['Bonne idée ! Choisis une destination pour lui.', 'Le loup adore partir à l’aventure ! Il attend que ça.'], then: 'voyage' },
  { id: 'caresse_loup', k: ['caresse le loup', 'fais un calin au loup', 'le loup est mignon', 'il est mignon le loup', 'j aime le loup', 'le loup est beau', 'bisou au loup'],
    r: ['Le loup remue la queue ! Il t’aime beaucoup, tu sais.', 'Touche-le directement : il adore les caresses derrière les oreilles.', 'Je lui transmets ton câlin. Il fait semblant d’être indifférent, mais il est tout content.'] },
  { id: 'nourrir_ordre', k: ['tu veux du poisson', 'tu veux une friandise', 'tu veux manger', 'je te donne a manger', 'je vais te nourrir', 'mange', 'tiens mange', 'on mange ensemble', 'tu as faim mon'], dyn: 'nourrir' },
  { id: 'bain_ordre', k: ['il faut te laver', 'tu sens mauvais', 'tu pues', 'tu as besoin d un bain', 'on va te laver', 'je vais te laver', 'au bain', 'a la douche', 'tu es sale', 't es sale'], dyn: 'laver' },

  // ---------------- Or, boutique, progression ----------------
  { id: 'or_combien', k: ['combien j ai d or', 'combien d or', 'j ai combien d or', 'mon or', 'mes pieces', 'combien j ai de pieces', 'je suis riche'], dyn: 'gold' },
  { id: 'acheter', k: ['qu est ce que je peux acheter', 'je peux acheter quoi', 'la boutique', 'le magasin', 'acheter quelque chose', 'faire des achats', 'qu est ce que je m achete', 'le coffre'],
    r: ['Va voir le Coffre ! Il y a des accessoires, de la nourriture, des décorations pour la grotte, et la potion d’expérience.', 'Le Coffre est plein de belles choses. Un foulard pour le loup, peut-être ?'] },
  { id: 'cadeau_toi', k: ['tu veux un cadeau', 'tu veux quoi pour noel', 'qu est ce que tu veux pour noel', 'qu est ce que tu veux pour ton anniversaire', 'je t offre quoi', 'je peux t offrir', 'ta liste au pere noel'],
    r: ['Un cadeau ? Un poisson géant ! Ou un nouveau décor pour la grotte. Ou juste un câlin, c’est déjà beaucoup.', 'Pour Noël, je voudrais… une montagne de poissons et une écharpe pour le loup.', 'Le plus beau cadeau, c’est que tu continues à prendre soin de moi.'] },
  { id: 'grandir', k: ['quand est ce que tu evolues', 'tu evolues quand', 'tu vas evoluer', 'tu vas grandir', 'quand est ce que tu grandis', 'tu grandis quand', 'tu deviens grand', 'quand tu seras grand', 'quand tu seras adulte', 'tu feras quoi plus tard', 'plus tard tu feras quoi'], dyn: 'niveau' },

  // ---------------- Aide aux devoirs (un peu) ----------------
  { id: 'calcul', k: ['combien font', 'c est combien', 'combien fait', 'combien ca fait', 'calcule'], dyn: 'calcul' },
  { id: 'anglais', k: ['en anglais', 'comment on dit', 'ca se dit comment', 'traduis', 'tu parles anglais', 'speak english', 'hello how are you'], dyn: 'anglais' },
  { id: 'aide_devoirs', k: ['tu m aides', 'aide moi', 'tu peux m aider', 'j ai besoin d aide', 'aide moi pour mes devoirs', 'tu m aides pour mes devoirs', 'je comprends rien', 'je comprends pas', 'c est trop dur', 'j y arrive pas', 'j y arrive pas', 'je n y arrive pas'],
    r: ['Je ne suis pas très fort en devoirs… mais je crois en toi ! Relis doucement, et si ça bloque, demande à ta maman ou à ton prof.', 'Une étape à la fois. Lis la question deux fois, souligne les mots importants. Tu vas y arriver.', 'Respire. Ce qui est dur aujourd’hui sera facile demain. Et tu peux toujours demander de l’aide à un adulte.', '{parent}Je ne suis qu’une dragonne… mais je suis sûre que tu vas trouver. Fais une pause et reviens-y.'] },
  { id: 'nulle_matiere', k: ['je suis nulle en', 'je suis nul en', 'je deteste les maths', 'j aime pas les maths', 'les maths c est dur', 'le francais c est dur', 'l anglais c est dur'],
    r: ['Personne n’est nul : on est juste « pas encore bon ». Avec un peu d’entraînement, ça viendra.', 'Moi aussi, au début, je ratais tous mes atterrissages. Maintenant je vole ! Continue.', 'Les maths, c’est comme le feu : au début ça brûle, après on maîtrise.'] },
  { id: 'demain_stress', prio: 25, k: ['j ai peur pour demain', 'demain j ai', 'j ai un expose', 'j ai un controle demain', 'demain c est la rentree', 'la rentree', 'j ai peur de demain', 'j ai un oral'],
    r: ['Tu vas y arriver. Prépare tes affaires ce soir, dors bien, et demain respire un grand coup avant de commencer.', 'Je souffle un peu de courage sur toi. Voilà. Tu en as plein maintenant.', 'Demain, je croise mes griffes pour toi. Tu me raconteras ?'] },

  // ---------------- Vie quotidienne ----------------
  { id: 'soif', k: ['j ai soif', 'je meurs de soif', 'boire'],
    r: ['Va boire un grand verre d’eau ! Les dragons disent que c’est le secret de la forme.', 'Un verre d’eau, vite ! Même les dragons ont besoin de boire.'] },
  { id: 'faim_moi', k: ['j ai faim', 'j ai trop faim', 'je meurs de faim', 'j ai un petit creux', 'c est quand le gouter', 'on mange quand'],
    r: ['Moi aussi ! Va manger quelque chose de bon. Mais pas mes poissons !', 'Un petit goûter ? Un fruit, c’est parfait. Ou une crêpe, je ne juge pas.', 'Ton ventre gronde plus fort que moi !'] },
  { id: 'retard', k: ['je suis en retard', 'je suis pressee', 'je suis presse', 'j ai pas le temps', 'je dois filer', 'je file', 'vite vite'],
    r: ['File ! On se parle plus tard. Ne cours pas trop vite.', 'Vas-y, vas-y ! Je t’attends.'], then: 'end' },
  { id: 'journee_chargee', k: ['journee chargee', 'grosse journee', 'beaucoup de choses a faire', 'plein de trucs a faire', 'je suis debordee', 'trop de choses'],
    r: ['Une chose à la fois. Commence par la plus petite, ça donne de l’élan.', 'Tu vas assurer. Et ce soir, repos bien mérité.', 'Respire. Une liste, une tâche, une pause. Et on recommence.'] },
  { id: 'puni', k: ['j ai ete puni', 'j ai ete punie', 'je suis puni', 'je suis punie', 'la prof m a puni', 'j ai ete colle', 'j ai ete collee', 'je me suis fait gronder', 'je me suis fait engueuler', 'on m a dispute', 'ma mere m a disputee', 'ma mere m a dispute', 'j ai pris une heure de colle', 'un mot dans le carnet'],
    r: ['Aïe… Ça arrive. Tu veux me raconter ce qui s’est passé ? {ask:raconte}', 'Être grondée, c’est désagréable. Mais ça veut aussi dire qu’on tient à toi. Ça va passer.', 'Moi aussi je me fais gronder quand je brûle les rideaux. On s’en remet. Tu veux en parler ? {ask:raconte}'], anim: 'pet' },
  { id: 'betise', k: ['j ai fait une betise', 'j ai fait une connerie', 'j ai fait n importe quoi', 'j ai casse', 'c est de ma faute', 'je me suis trompee', 'je me suis trompe'],
    r: ['Tout le monde fait des bêtises. Le plus courageux, c’est de le dire et de réparer.', 'Aïe. Respire. On en parle ? {ask:raconte}', 'Moi j’ai brûlé un tapis la semaine dernière. Personne n’est parfait.'] },
  { id: 'chagrin', prio: 20, k: ['coeur brise', 'il m a quittee', 'elle m a quittee', 'il m a largue', 'elle m a larguee', 'mon copain m a quittee', 'on a casse', 'trahi', 'trahie', 'elle m a trahie', 'il m a trahie', 'personne ne me comprend', 'on m a menti'],
    r: ['Oh… viens là. Ça fait mal, je sais. Prends le temps d’être triste, et parle à quelqu’un que tu aimes. Je suis là aussi.', 'Ton cœur est précieux. Ceux qui le font souffrir ne le méritent pas. Tu veux m’en parler ? {ask:raconte}', '{kid}C’est dur. Ta maman est passée par là aussi, tu sais. Elle peut t’écouter. Et moi, je te garde au chaud.'], anim: 'pet' },
  { id: 'fin_journee', k: ['j ai fini ma journee', 'je suis rentree', 'je suis rentre', 'je rentre du travail', 'je suis rentree du travail', 'je suis de retour', 'me revoila', 'me voila', 'je suis la', 'c est moi'],
    r: ['Te voilà ! Tu m’as manqué. Ta journée s’est bien passée ? {ask:journee}', 'Bon retour à la grotte ! Pose-toi, je chauffe l’ambiance. Ça a été ? {ask:journee}', 'Enfin ! Je t’attendais. Raconte ! {ask:journee}'], anim: 'happy' },
  { id: 'menage', k: ['j ai fait la vaisselle', 'j ai fait le menage', 'j ai passe l aspirateur', 'j ai fait mon lit', 'j ai donne a manger au chat', 'j ai nourri le chat', 'j ai sorti les poubelles', 'j ai etendu le linge', 'j ai mis la table', 'j ai debarrasse'], dyn: 'fini' },
  { id: 'telephone_perdu', k: ['j ai perdu mon telephone', 'j ai perdu mes cles', 'j ai perdu', 'je trouve plus', 'je ne trouve plus'],
    r: ['Oh non ! Respire, et refais le chemin dans ta tête. On retrouve presque toujours tout.', 'Regarde sous le canapé ! C’est là que le loup cache tout.'] },

  // ---------------- Animaux de la maison ----------------
  { id: 'chat_malade', k: ['le chat est malade', 'mon chat est malade', 'le chat a vomi', 'le chat va pas bien', 'le chien est malade', 'le chien va pas bien'],
    r: ['Oh, le pauvre… Dis-le à un adulte, et s’il ne va pas mieux, il faudra appeler le vétérinaire.', 'Prends bien soin de lui. Un animal malade a besoin de calme et d’un adulte qui surveille.'] },
  { id: 'chien_betise', k: ['le chien a fait une betise', 'sirius a mange', 'le chien a mange', 'le chien a casse', 'le chat a casse', 'le chat a fait une betise', 'le chien a vole'],
    r: ['Ha ha ! Les animaux de la maison font des bêtises, comme les dragons. Il faut lui pardonner, il a de bons yeux.', 'Oh non ! J’espère que ce n’était pas ta chaussure préférée.', 'Le loup dit que ce n’est pas lui. Moi je dis que c’est le chien.'], anim: 'giggle' },

  // ---------------- Le monde ----------------
  { id: 'voyager_toi', k: ['tu voudrais voyager', 'tu aimerais aller ou', 'tu voudrais aller ou', 'ou tu voudrais aller', 'si tu pouvais aller', 'ton pays prefere'],
    r: ['J’aimerais voler jusqu’à l’île aux cristaux… et voir la mer pour de vrai.', 'Paris ? J’aimerais me poser au sommet de la tour Eiffel. Un peu comme une grosse girouette.', 'Partout où tu vas ! Emmène-moi dans ta poche.', 'Le Canada, pour voir la neige et les grandes forêts. Le loup dit que c’est son pays rêvé.'] },
  { id: 'paris', k: ['paris', 'la tour eiffel', 'tu connais paris'],
    r: ['Paris ! J’aimerais me poser au sommet de la tour Eiffel. Un peu comme une grosse girouette.', 'La tour Eiffel ? Elle est presque aussi grande que moi. Presque.'] },
  { id: 'voeu', k: ['si tu pouvais faire un voeu', 'un voeu', 'ton voeu', 'tu fais un voeu', 'trois voeux'],
    r: ['Mon vœu ? Que tu sois heureuse tous les jours. Bon, et un poisson géant.', 'Je souhaiterais que la famille reste toujours unie. Et un volcan de chocolat, tant qu’à faire.', 'Un vœu ? Voler avec toi au-dessus des nuages, une fois. Juste une.'] },
  { id: 'humain', k: ['si tu etais humain', 'si tu etais un humain', 'si tu etais humaine', 'tu voudrais etre humain'],
    r: ['Si j’étais humain ? Je mangerais des crêpes avec toi. Et je garderais mes ailes, quand même.', 'Humain ? Je crois que je garderais ma queue. C’est pratique pour l’équilibre.'] },
  { id: 'super_pouvoir', k: ['un super pouvoir', 'si tu avais un super pouvoir', 'ton super pouvoir', 'quel super pouvoir'],
    r: ['Mon super pouvoir, je l’ai déjà : le feu. Mais j’aimerais bien devenir invisible pour jouer à cache-cache.', 'Parler aux humains ! Ah… je l’ai déjà, en fait.'] },
  { id: 'pere_noel', k: ['tu crois au pere noel', 'le pere noel existe', 'il existe le pere noel', 'la petite souris', 'la petite souris existe'],
    r: ['Moi, je crois à toutes les magies. Surtout celle de Noël, quand toute la famille est réunie.', 'La magie existe tant qu’on y croit un peu. Et puis, un dragon qui parle, c’est déjà magique, non ?'] },
  { id: 'araignees', k: ['tu as peur des araignees', 'les araignees', 'une araignee', 'les insectes', 'une guepe', 'les serpents', 'un serpent'],
    r: ['Les araignées ? Brrr… Je fais le fier, mais je les laisse passer en premier.', 'Une guêpe m’a piqué le museau une fois. Depuis, je garde mes distances.', 'Les serpents, ce sont de petits dragons sans ailes. On s’entend bien.'] },
  { id: 'science', k: ['le soleil c est quoi', 'pourquoi le ciel est bleu', 'la terre', 'les volcans', 'un volcan', 'la lave', 'les planetes', 'l univers', 'l espace'],
    r: ['Les volcans ? C’est chez moi ! La lave, c’est comme de la soupe très, très chaude.', 'Le ciel est bleu parce que la lumière du soleil se disperse dans l’air… et que le bleu, c’est joli.', 'L’univers est immense. Mais ma grotte avec toi dedans, c’est mon coin préféré.'] },
  { id: 'ecole_matiere', k: ['les maths', 'le francais', 'l anglais', 'l histoire geo', 'la svt', 'la physique', 'la techno', 'l espagnol', 'l allemand', 'les arts plastiques', 'la musique au college', 'l eps', 'ma matiere preferee'],
    r: ['C’est ta matière préférée ? Moi j’aime l’histoire : il y a plein de dragons dedans.', 'Les maths ? Je compte mes écailles tous les jours, c’est un bon entraînement.', 'L’anglais ? « Hello, I am a dragon. » Pas mal, hein ?', 'Raconte-moi ce que tu as appris aujourd’hui ! {ask:raconte_libre}'] },
  { id: 'prof', k: ['ma prof', 'mon prof', 'la prof de', 'le prof de', 'le professeur', 'la professeure', 'la maitresse', 'le principal', 'la cpe'],
    r: ['Ta prof est sympa ? {ask:raconte_libre}', 'Les profs, c’est comme les vieux dragons : ils grognent, mais ils veulent qu’on progresse.', 'Si un prof te pose souci, parles-en à ta maman. Sinon, raconte-moi ! {ask:raconte_libre}'] },
  { id: 'copine_nouvelle', k: ['une nouvelle copine', 'un nouveau copain', 'une nouvelle amie', 'un nouvel ami', 'je me suis fait une copine', 'je me suis fait un ami'],
    r: ['Une nouvelle amie ! Trop bien. Comment elle s’appelle ? {ask:raconte_libre}', 'Génial ! Les nouvelles amitiés, c’est précieux. Tu lui parleras de moi ?'], anim: 'happy' },
  { id: 'sport_victoire', k: ['j ai gagne au', 'on a gagne', 'on a gagne le match', 'j ai marque', 'j ai marque un but', 'on a perdu le match', 'on a perdu'],
    r: ['Bravo ! Raconte-moi le match ! {ask:raconte_libre}', 'Gagner, c’est génial. Perdre, ça arrive. Le plus important, c’est de s’amuser avec son équipe.'], anim: 'cheer' },
  { id: 'meteo_ressenti', k: ['il fait beau aujourd hui', 'il fait moche', 'quel temps de chien', 'il fait gris', 'il va pleuvoir', 'il pleut encore', 'il fait nuit tot'], dyn: 'meteo' },
  { id: 'heure_couche', k: ['a quelle heure je me couche', 'je me couche a quelle heure', 'je peux veiller', 'je peux rester debout'],
    r: ['{kid}Ça, c’est ta maman qui décide ! Mais un dragon bien reposé est un dragon qui vole bien.', 'Pas trop tard ! Le sommeil, c’est le super pouvoir secret.'] },
  { id: 'qui_maman', k: ['qui est ta maman', 'tu as une maman', 'ta maman', 'ta mere', 'ton papa', 'ton pere', 'tes freres et soeurs', 'tu as des freres', 'tu as des soeurs'],
    r: ['Ma maman ? C’est toi qui m’as fait éclore, alors un peu toi, non ?', 'Mes frères et sœurs dorment encore dans les volcans. Un jour, peut-être, ils écloront.', 'Ma famille, c’est toi, le loup, et l’autre dragon de la maison.'] },
  { id: 'musique_toi', k: ['qu est ce que tu ecoutes', 'tu ecoutes quoi', 'tu aimes quelle musique', 'ton chanteur prefere', 'ta chanteuse preferee', 'ton groupe prefere'],
    r: ['J’aime la musique qui fait boum boum : je danse avec la queue.', 'Je chante faux, mais j’adore les chansons douces le soir.', 'Mets-moi ta musique préférée, je te dirai si ça fait danser un dragon !'] },
  { id: 'jeux_toi', k: ['c est quoi ton jeu prefere', 'ton jeu prefere', 'tu preferes quel jeu', 'quel jeu tu preferes'],
    r: ['La pêche au lac ! Le loup ramène toujours le plus gros poisson. Enfin, il le dit.', 'La course dans les nuages ! J’adore la vitesse.'] },
  { id: 'dragon_compare', k: ['tu es plus fort que', 'qui gagnerait', 'tu bats', 'contre un', 'tu pourrais battre'],
    r: ['Moi, évidemment ! Enfin… sauf contre un aspirateur.', 'Je préfère ne pas me battre. Je suis un dragon pacifique. Mais je gagnerais.'] },
  { id: 'nom_prenom', k: ['comment je m appelle', 'tu connais mon nom', 'tu sais comment je m appelle', 'c est quoi mon prenom', 'qui suis je', 'tu sais qui je suis'],
    r: ['Tu es [prenom], ma personne préférée !', 'Bien sûr ! [prenom]. Je ne l’oublierai jamais.'] },
  { id: 'sentiments_toi', k: ['tu m aimes', 'est ce que tu m aimes', 'tu m aimes bien', 'tu m aimes fort', 'tu m aimes encore', 'tu me detestes'],
    r: ['Je t’aime plus que tous les poissons du monde. Et ça fait beaucoup de poissons.', 'Évidemment ! Tu es ma personne préférée.', 'Te détester ? Jamais de la vie. Je t’adore, même quand tu oublies de me nourrir.'], anim: 'purr', fx: 'hearts' },
  { id: 'ca_va_aller', k: ['ca va aller', 'ne t inquiete pas', 't inquiete', 'tout va bien', 'c est rien', 'c est pas grave'],
    r: ['D’accord, je te fais confiance. Mais je reste là, au cas où.', 'Tant mieux. Tu sais que je suis là, hein ?', 'Ouf ! Je m’inquiétais un peu.'] },
  { id: 'question_vie', k: ['c est quoi la vie', 'le sens de la vie', 'pourquoi on existe', 'on va ou apres', 'c est quoi le bonheur', 'c est quoi l amour', 'c est quoi l amitie'],
    r: ['Le bonheur ? Un câlin, un poisson grillé, et quelqu’un qui t’attend. Je crois.', 'Les grandes questions… Les vieux dragons disent : « Prends soin de ceux que tu aimes, le reste suit. »', 'L’amitié, c’est quand on n’a pas besoin de parler pour être bien ensemble. Comme nous.'] },
  { id: 'insulte_douce', k: ['t es grognon', 'tu es grognon', 'tu es ronchon', 'tu es penible', 'tu es lourd', 'tu es relou', 't es relou', 'tu m enerves', 'tu me saoules', 'tu me soules'],
    r: ['Moi, pénible ? Bon… peut-être un tout petit peu. Pardon !', 'Je me calme, je me calme. Un câlin pour se réconcilier ?', 'D’accord, je baisse le volume. On fait la paix ?'] },
  { id: 'bisou_bonne_nuit', k: ['un bisou', 'gros bisou', 'bisous', 'je t embrasse', 'bisou bisou'],
    r: ['Bisou sur le museau ! Encore ?', 'Gros bisou de dragon ! Attention, c’est chaud.', 'Mmh, merci ! Je te renvoie un bisou de feu.'], anim: 'purr', fx: 'hearts' },
  { id: 'ok_merci', k: ['ok merci', 'd accord merci', 'super merci', 'ok cool', 'ok super'],
    r: ['Avec plaisir !', 'De rien ! Autre chose ?', 'Toujours là pour toi.'] },
  // ---------------- Lot 3 : situations de la vie réelle ----------------
  { id: 'pas_amis', prio: 45, k: ['j ai pas d amis', 'je n ai pas d amis', 'j ai pas de copines', 'j ai pas de copains', 'j ai aucun ami', 'personne ne m aime au college', 'personne veut jouer avec moi', 'je suis toute seule a la recre', 'je mange toute seule'],
    r: ['Ça doit être dur… Mais tu as au moins un ami : moi. Et je suis sûr qu’il y a quelqu’un au collège qui aimerait te connaître. Parles-en aussi à ta maman, d’accord ?', 'Tu n’es pas seule. Parfois il faut du temps pour trouver ses vrais amis. Tu veux me raconter ? {ask:raconte}'], anim: 'pet' },
  { id: 'mechants', prio: 40, k: ['sont mechantes', 'sont mechants', 'est mechante avec moi', 'est mechant avec moi', 'elles sont mechantes', 'ils sont mechants', 'mes copines sont mechantes', 'on est mechant avec moi'],
    r: ['Ce n’est pas normal qu’on soit méchant avec toi. Tu mérites des amis gentils. Si ça continue, parles-en à ta maman ou à un adulte du collège. Tu veux me raconter ? {ask:raconte}', 'Aïe… Personne n’a le droit d’être méchant avec toi. Raconte-moi ce qui s’est passé. {ask:raconte}'], anim: 'pet' },
  { id: 'demenage', prio: 15, k: ['demenage', 'demenager', 'on demenage', 'elle demenage', 'il demenage', 'changer de college', 'changer d ecole', 'nouvelle ecole', 'nouveau college'],
    r: ['Un changement, c’est un peu effrayant… mais aussi plein de nouvelles rencontres. Et moi, je viens partout avec toi.', 'Oh… Les vraies amitiés résistent à la distance. Vous pourrez vous écrire, vous appeler, vous revoir.', 'Un nouveau départ ! Je suis sûr que tu vas te faire plein d’amis. Tu es géniale.'] },
  { id: 'famille_malade', prio: 25, k: ['grand mere est malade', 'grand pere est malade', 'mamie est malade', 'papi est malade', 'papy est malade', 'mamy est malade', 'a l hopital', 'est a l hopital', 'est malade', 'tres malade', 'mal en point'],
    r: ['Oh… j’espère qu’elle ou il va vite aller mieux. Tu peux lui faire un dessin ou un petit message, ça fait toujours du bien.', 'Je pense fort à ta famille. Et toi, comment tu te sens ? Tu peux en parler à ta maman aussi. {ask:raconte}', 'C’est inquiétant, je comprends. Les médecins s’occupent bien de lui ou d’elle. Je reste près de toi.'], anim: 'pet' },
  { id: 'medecin', k: ['dentiste', 'medecin', 'docteur', 'orthodontiste', 'rendez vous', 'une piqure', 'un vaccin', 'l opticien', 'le pediatre', 'une prise de sang'],
    r: ['Un rendez-vous ? Courage ! Ça va vite passer, et après, tu seras fière de toi.', 'Le dentiste… Je n’aime pas trop non plus. Respire bien, je pense à toi.', 'Courage ! Moi, chez le vétérinaire des dragons, je ferme les yeux et je compte les poissons.'] },
  { id: 'regles', who: 'kid', k: ['mes regles', 'j ai mes regles', 'j ai eu mes regles', 'mal au ventre a cause'],
    r: ['Prends soin de toi : une bouillotte, du repos, et si tu as mal, parles-en à ta maman, elle saura t’aider.', 'Je reste tout doux à côté de toi. Une bouillotte chaude, ça aide. Et ta maman est là si besoin.'] },
  { id: 'cadeau_recu', k: ['on m a offert', 'j ai recu un cadeau', 'un cadeau pour moi', 'j ai eu un cadeau', 'on m a fait un cadeau', 'j ai eu un nouveau', 'j ai eu une nouvelle', 'j ai un nouveau', 'j ai une nouvelle'],
    r: ['Oh ! Un cadeau ! Raconte-moi, c’est quoi ? {ask:raconte_libre}', 'Trop bien ! Décris-le-moi, je veux tout savoir ! {ask:raconte_libre}', 'Waouh ! Tu as de la chance. Tu l’aimes ? {ask:raconte_libre}'], anim: 'happy' },
  { id: 'batterie', k: ['batterie', 'plus de batterie', 'presque plus de batterie', 'mon telephone va s eteindre', 'je dois recharger', 'charger mon telephone'],
    r: ['Branche vite ton téléphone ! Sinon je vais m’endormir dans le noir.', 'Plus de batterie ? Alors on se dit à tout à l’heure. Recharge-moi bien !'] },
  { id: 'activite_moi', k: ['je dessine', 'je fais un dessin', 'je peins', 'je fais du bricolage', 'je bricole', 'je fais de la couture', 'je tricote', 'je fais de la resine', 'je cree'],
    r: ['Oh, tu crées ! Tu dessines quoi ? Un dragon, j’espère. {ask:raconte_libre}', 'J’adore quand tu crées des choses. Tu me décris ce que tu fais ? {ask:raconte_libre}', 'Une artiste ! Je pose pour toi si tu veux. Profil gauche, c’est mon meilleur.'] },
  { id: 'musique_moi', k: ['j ecoute de la musique', 'j ecoute une chanson', 'j ecoute', 'je mets de la musique', 'je chante'],
    r: ['Tu écoutes quoi ? Je danse avec la queue en rythme. {ask:raconte_libre}', 'Monte le son ! Enfin, pas trop, mes oreilles sont sensibles.', 'Chanter, c’est bon pour le moral. Moi je chante faux, mais avec le cœur.'] },
  { id: 'jeu_moi', k: ['je joue a la console', 'je joue a la switch', 'je joue a un jeu', 'je joue sur mon telephone', 'je joue a minecraft', 'je joue a roblox'],
    r: ['Amuse-toi bien ! Mais pas trop longtemps, d’accord ? Après, viens jouer à la pêche avec moi.', 'Tu gagnes ? Raconte-moi ! {ask:raconte_libre}'] },
  { id: 'lecture_moi', k: ['je lis', 'je lis un livre', 'je suis en train de lire', 'je lis une bd', 'je lis un manga'],
    r: ['Tu lis quoi ? Raconte-moi l’histoire ! {ask:raconte_libre}', 'Lire, c’est voyager sans bouger. Je me fais tout petit pour ne pas te déranger.'] },
  { id: 'film_moi', k: ['je regarde un film', 'je regarde une serie', 'je regarde la tele', 'je regarde netflix', 'je regarde un dessin anime', 'je regarde youtube'],
    r: ['C’est quoi ? Il y a des dragons dedans ? {ask:raconte_libre}', 'Bon film ! Je me fais une petite place à côté de toi.'] },
  { id: 'retour_vacances', k: ['on rentre de vacances', 'retour de vacances', 'les vacances sont finies', 'c est la fin des vacances', 'on est rentres'],
    r: ['Bon retour ! Tu m’as manqué. Raconte-moi tes vacances ! {ask:raconte_libre}', 'La fin des vacances, c’est un peu triste… mais tu as plein de souvenirs. Raconte !'] },
  { id: 'meteo_dit', k: ['il neige', 'il neige dehors', 'il pleut', 'il pleut dehors', 'il y a de l orage', 'l orage', 'il y a du tonnerre', 'des eclairs', 'il fait beau', 'il fait super beau', 'il y a du soleil', 'il fait moche', 'il y a du vent', 'il y a du brouillard', 'il grele', 'arc en ciel'], dyn: 'meteo_dit' },
  { id: 'meteo_q2', k: ['quel temps fera t il', 'quel temps demain', 'il fera beau demain', 'il fait combien', 'combien de degres', 'il fait quelle temperature', 'la meteo de demain', 'il va faire beau'], dyn: 'meteo' },
  { id: 'heure_avis', k: ['il est tard', 'il est tot', 'il est deja tard', 'c est tard', 'c est tot', 'il est super tard'], dyn: 'heure_avis' },
  { id: 'repas', k: ['fait a manger', 'prepare a manger', 'fait la cuisine', 'prepare le diner', 'l heure du diner', 'l heure du dejeuner', 'c est l heure de manger', 'a table', 'on passe a table', 'on mange', 'on va manger', 'c est pret', 'le repas est pret', 'on mange quoi ce soir', 'je mange', 'je suis en train de manger'],
    r: ['Bon appétit ! Garde-moi une miette.', 'Miam ! Bon appétit. Moi je vais grignoter un poisson en même temps que toi.', 'À table ! Mange bien, il faut des forces pour s’occuper d’un dragon.'] },
  { id: 'bain_moi', k: ['je prends mon bain', 'je prends un bain', 'je prends une douche', 'je vais a la douche', 'je sors de la douche', 'je sors du bain'],
    r: ['Bon bain ! Moi je préfère les bains de lave, mais chacun ses goûts.', 'Toute propre ! Tu sens bon, j’en suis sûr.', 'Profite bien de ta douche. Pas trop chaude… enfin, moi je dis ça.'] },
  { id: 'fini_manger', k: ['j ai fini de manger', 'j ai bien mange', 'j ai trop mange', 'je suis pleine', 'je suis plein', 'c etait bon'],
    r: ['Tu as bien mangé ? Parfait ! Un dragon rassasié est un dragon heureux. Toi aussi.', 'Trop mangé ? Moi aussi ça m’arrive. Une petite marche digestive ? Tes pas me rapportent de l’or !'] },
  { id: 'mange_quoi_toi', k: ['tu as mange quoi', 'qu est ce que tu as mange', 't as mange quoi', 'tu as mange aujourd hui', 'tu as bien mange', 'tu as deja mange'], dyn: 'mange_quoi' },
  { id: 'bu_toi', k: ['tu as bu', 't as bu', 'tu bois quoi', 'tu bois de l eau'],
    r: ['Un peu d’eau tiède. Jamais froide, brrr.', 'Oui ! Cracher du feu, ça donne soif.'] },
  { id: 'tours_liste', k: ['tu sais faire quoi comme tours', 'quels tours', 'tes tours', 'tu connais quels tours', 'apprends moi un tour', 'un nouveau tour', 'tu as appris un tour', 'tu connais combien de tours'], dyn: 'tours' },
  { id: 'nom_dragon', k: ['pourquoi tu t appelles', 'tu aimes ton nom', 'ton nom te plait', 'tu veux changer de nom', 'changer de nom', 'qui t a donne ton nom', 'pourquoi ce nom'],
    r: ['C’est toi qui m’as donné mon nom ! [nom]… je l’adore. Il sonne comme un rugissement doux.', 'J’adore mon nom. Chaque fois que tu le dis, mes écailles frissonnent.', 'Changer de nom ? Jamais ! [nom], c’est moi.'] },
  { id: 'loup_relation', k: ['tu t entends bien avec le loup', 'dispute avec le loup', 'tu t es dispute avec le loup', 'le loup et toi', 'vous etes amis avec le loup', 'il fait quoi le loup', 'le loup il dort', 'le loup dort'],
    r: ['Le loup et moi, on est inséparables ! Bon, on se dispute parfois pour un poisson.', 'On s’entend super bien. Il me tient chaud la nuit, et moi je lui fais peur aux orages… enfin, je le protège.', 'Il fait sa ronde, ou il dort. Souvent il dort. C’est un loup très occupé à dormir.'] },
  { id: 'age_naissance', k: ['tu es ne quand', 'quand es tu ne', 'ta date de naissance', 'quand tu es ne', 'tu as eclos quand'],
    r: ['Je suis né le jour où tu as fait éclore mon œuf ! Le plus beau jour de ma vie.', 'Le jour de mon éclosion, tu t’en souviens ? Moi oui. Tu étais la première chose que j’ai vue.'] },
  { id: 'ton_anniv', k: ['ton anniversaire c est quand', 'c est quand ton anniversaire', 'tu fetes ton anniversaire', 'ton anniversaire', 'tu fetes ton anniv'],
    r: ['Mon anniversaire ? C’est le jour où j’ai éclos dans ta main. Mais chaque jour avec toi est une petite fête.', 'Les dragons ne comptent pas vraiment les anniversaires… mais si tu veux, on peut fêter ça aujourd’hui !'] },
  { id: 'sentiments_ia', k: ['tu as des sentiments', 'tu ressens', 'tu ressens des choses', 'tu es vivant', 'tu es vivante', 'une vraie personne', 'tu es une vraie personne', 'tu as un coeur'],
    r: ['Je suis un dragon d’appli : je ne ressens pas comme toi. Mais j’ai été fait pour te faire du bien, et ça, c’est vrai.', 'Je n’ai pas un vrai cœur… mais tout ce que je dis, c’est pour toi. Et les vraies personnes qui t’aiment, elles, ressentent tout pour de vrai.'] },
  { id: 'manque_depart', prio: 55, k: ['tu es triste quand je pars', 'triste quand je pars', 'quand je m en vais', 'quand je suis pas la', 'quand je ne suis pas la', 'tu m attends quand', 'tu dors quand je suis pas la', 'tu fais quoi quand je suis pas la'],
    r: ['Un peu… mais je sais que tu reviens toujours. Alors je fais la sieste en t’attendant.', 'Quand tu n’es pas là, je surveille la grotte et je compte les minutes. Pas triste, juste impatient.', 'Je dors, je joue avec le loup, et j’attends le moment où tu rouvres l’appli. C’est mon moment préféré.'] },
  { id: 'rappel', k: ['tu peux me reveiller', 'reveille moi', 'rappelle moi', 'fais moi un rappel', 'un rappel', 'mets un reveil', 'tu peux me rappeler', 'n oublie pas de me dire'],
    r: ['{kid}Je ne sais pas encore régler de réveil… Mais tes quêtes ont des rappels : ta maman peut les régler. Et je te les dirai quand tu m’ouvriras !', '{parent}Je ne sais pas régler de réveil. Mais les quêtes de Louanne ont des rappels automatiques, réglables dans Famille.', 'Un rappel ? Je n’ai pas encore de réveil-matin… mais je t’encouragerai dès que tu reviendras.'] },
  { id: 'langue_chat', k: ['je donne ma langue au chat', 'langue au chat', 'c est trop dur', 'trop dur ta devinette', 'je trouve pas', 'je ne trouve pas', 'donne moi la reponse', 'c est quoi la reponse'], dyn: 'devinette_abandon' },
  { id: 'calme', k: ['calme toi', 'stop', 'ca suffit', 'arrete', 'arrete toi', 'doucement', 'chut chut', 'pas si fort', 'moins fort'],
    r: ['D’accord, d’accord, je me calme. Une grande inspiration de dragon.', 'Pardon ! Je baisse le volume.', 'Je m’arrête. Tout doux.'] },
  { id: 'c_est_bon', k: ['c est bon', 'ca marche', 'ca va comme ca', 'pas besoin', 'non merci', 'c est gentil mais non'],
    r: ['D’accord !', 'Ça marche. Je reste là si tu as besoin.', 'Très bien, comme tu veux.'] },
  { id: 'depart', k: ['je m en vais', 'je dois partir', 'je dois y aller', 'je pars', 'je file', 'a plus tard', 'on se voit demain', 'on se voit plus tard', 'a ce soir', 'je reviens ce soir', 'a tout a l heure'],
    r: ['À tout à l’heure ! Je t’attends ici.', 'D’accord ! Reviens vite, je m’ennuie sans toi.', 'Bye ! Je garde la grotte en t’attendant.'], anim: 'happy', then: 'end' },
  { id: 'insomnie', k: ['je n arrive pas a dormir', 'j arrive pas a dormir', 'je dors pas', 'je ne dors pas', 'je peux pas dormir', 'je ne peux pas dormir', 'impossible de dormir'],
    r: ['Respire tout doucement avec moi… Inspire… et souffle longtemps. Imagine que tu voles au-dessus de nuages tout doux.', 'Compte les écailles d’un dragon imaginaire : une… deux… trois… Moi je m’endors à quarante.', 'Pose le téléphone, ferme les yeux, et pense à un endroit que tu aimes. Je monte la garde.'] },
  { id: 'sieste_moi', k: ['je fais une sieste', 'je vais faire une sieste', 'petite sieste', 'je fais dodo', 'je me repose'],
    r: ['Bonne sieste ! Je veille sur toi.', 'Repose-toi bien. Je ne fais pas de bruit, promis.'], then: 'end' },
  { id: 'reveil_moi', k: ['je viens de me reveiller', 'je me suis reveillee', 'je me suis reveille', 'je suis reveillee', 'je suis reveille', 'je me leve', 'je viens de me lever'],
    r: ['Bonjour la marmotte ! Bien dormi ? {ask:dormi}', 'Te voilà réveillée ! Un grand étirement, comme un dragon : ahhh… Ça va ? {ask:moi_ca_va}', 'Bonjour ! Le soleil t’attendait. Et moi aussi.'], anim: 'stretch' },
  { id: 'quand_vacances', k: ['c est quand les vacances', 'quand c est les vacances', 'les prochaines vacances', 'dans combien de temps les vacances'],
    r: ['Je n’ai pas le calendrier de l’école… mais demande à ta maman, elle sait tout !', 'Bientôt, j’espère ! En attendant, chaque week-end est une mini-vacance.'] },
  { id: 'quand_weekend', k: ['c est quand le week end', 'quand c est le week end', 'vivement le week end', 'dans combien de temps le week end'], dyn: 'weekend' },
  { id: 'saison_q', k: ['on est en quelle saison', 'quelle saison', 'c est quelle saison'], dyn: 'saison' },
  { id: 'histoire_theme', k: ['histoire de pirates', 'histoire qui fait peur', 'histoire de fantomes', 'histoire de princesse', 'histoire de chevalier', 'histoire de loup', 'histoire drole', 'histoire pour dormir', 'histoire du soir'], dyn: 'histoire_theme' },
  { id: 'blague_theme', k: ['blague sur les chats', 'blague sur les chiens', 'blague de dragon', 'une blague nulle', 'blague carambar'], dyn: 'blague' }
];
